### ISSUE TITLE
tenants list not match between brokers

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#4357] opened 2019-05-24 03:39 UTC
**Describe the bug**
user report data not match when run `pulsar-admin tenants list` on different brokers. And after reboot broker, it get syned.

**Expected behavior**
get same result when run `pulsar-admin tenants list` on different brokers.

**Screenshots**
![941558667436_ pic_hd](https://user-images.githubusercontent.com/6348208/58301223-2a916f80-7e18-11e9-8b16-387933b2aea3.jpg)

**Comment by jiazhai** [comment] 2019-05-24 03:48
A possible that will cause this isssue is zk disconnection. 
while broker disconnect with zk, other broker's change to zk were not able to be synced to the disconnect broker.
It would be good to refresh the zk data that cached in broker periodically, to avoid this error happen.

**Comment by sijie** [comment] 2019-05-26 09:21
@jiazhai 

I have worked with the engineer from huobi and figured out the problem. The problem is not in pulsar. The problem comes from a fall-behind zookeeper observer. 

They setup a 6 nodes global zookeeper cluster, which 3 observers. If the broker connects to an observer that falls behind, it will not get all the namespace policies. Hence the latest created namespace will not show up.

The problem is fixed by resetting that zookeeper observer.

**Closed** 2019-05-26 09:21 UTC
Labels: type/bug
