### ISSUE TITLE
KOP  getOffsetOfPosition failed ( Invalid unknonwn tag type: 6 )

### ISSUE THREAD

**Issue by xiaotongwang1** [apache/pulsar#12568] opened 2021-11-01 15:04 UTC
**配套版本**
pulsar: 2.8.1
KOP: 2.8.1.2

**复现场景：**

5台broker+5台bookie+5台zookeeper，3/3/2的模式

1、创建topic，启动生产者，没有消费者，持续发送数据
2、使用Kafka的API去获取Topic每个分区的消息first offset and last offset (handleListOffsetRequest getOffsetOfPosition)
3、持续发送数据，停止3台bookie，使集群不可用
4、启动3台bookie
5、使用Kafka的API去获取Topic每个分区的消息first offset and last offset (handleListOffsetRequest getOffsetOfPosition) ，失败，报错堆栈如下：

**KOP :**

2021-11-01 20:38:00.235 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR i.s.pulsar.handlers.kop.KafkaRequestHandler - publishMessages for topic partition: persistent://WiseCloudDMQService/WiseCloudDMQAminService/dmq.monitor-partition-1 failed when write.
org.apache.pulsar.broker.service.BrokerServiceException$PersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException: Not enough non-faulty bookies available
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.addFailed(PersistentTopic.java:543)
        at org.apache.bookkeeper.mledger.impl.OpAddEntry.failed(OpAddEntry.java:138)
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.clearPendingAddEntries(ManagedLedgerImpl.java:1680)
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.createComplete(ManagedLedgerImpl.java:1412)
        at org.apache.bookkeeper.client.LedgerCreateOp.createComplete(LedgerCreateOp.java:272)
        at org.apache.bookkeeper.client.LedgerCreateOp.initiate(LedgerCreateOp.java:166)
        at org.apache.bookkeeper.client.BookKeeper.asyncCreateLedger(BookKeeper.java:860)
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.asyncCreateLedger(ManagedLedgerImpl.java:3627)
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.ledgerClosed(ManagedLedgerImpl.java:1595)
        at org.apache.bookkeeper.mledger.impl.OpAddEntry.lambda$handleAddFailure$0(OpAddEntry.java:291)
        at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

2021-11-01 23:00:47.810 [BookKeeperClientWorker-OrderedExecutor-4-0] ERROR i.s.pulsar.handlers.kop.KafkaRequestHandler - [PersistentTopic{topic=persistent://WiseCloudDMQService/WiseCloudDMQAminService/dmq.monitor-partition-5}] Failed to get offset for position 603:0
io.streamnative.pulsar.handlers.kop.exceptions.KoPMessageMetadataNotFoundException: [603:0] Failed to peek offset from entry
        at io.streamnative.pulsar.handlers.kop.utils.MessageIdUtils.peekBaseOffsetFromEntry(MessageIdUtils.java:104)
        at io.streamnative.pulsar.handlers.kop.utils.MessageIdUtils$1.readEntryComplete(MessageIdUtils.java:80)
        at org.apache.bookkeeper.mledger.impl.EntryCacheImpl.lambda$asyncReadEntry0$0(EntryCacheImpl.java:229)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Broker**

2021-11-01 23:00:47.286 [BookKeeperClientWorker-OrderedExecutor-7-0] ERROR org.apache.pulsar.common.protocol.Commands - [null] [0] Failed to parse message metadata
java.lang.IllegalArgumentException: Invalid unknonwn tag type: 6
        at org.apache.pulsar.common.api.proto.LightProtoCodec.skipUnknownField(LightProtoCodec.java:270)
        at org.apache.pulsar.common.api.proto.MessageMetadata.parseFrom(MessageMetadata.java:1370)
        at org.apache.pulsar.common.protocol.Commands.parseMessageMetadata(Commands.java:429)
        at org.apache.pulsar.common.protocol.Commands.parseMessageMetadata(Commands.java:416)
        at org.apache.pulsar.common.protocol.Commands.peekMessageMetadata(Commands.java:1676)
        at io.streamnative.pulsar.handlers.kop.utils.MessageIdUtils.peekBaseOffsetFromEntry(MessageIdUtils.java:101)
        at io.streamnative.pulsar.handlers.kop.utils.MessageIdUtils$1.readEntryComplete(MessageIdUtils.java:80)
        at org.apache.bookkeeper.mledger.impl.EntryCacheImpl.lambda$asyncReadEntry0$0(EntryCacheImpl.java:229)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by BewareMyPower** [comment] 2021-11-02 02:16
> 使用Kafka的API去获取Topic每个分区的消息first offset and last offset (handleListOffsetRequest getOffsetOfPosition)

Please paste your code.

Another question is, did you stop sending messages after step 2? If I didn't understand wrong, you started a process to send messages continuously. Then stop bookies to make cluster not available.

Could you paste other error logs? Please don't hide these if you want more helps.

**Comment by BewareMyPower** [comment] 2021-11-02 02:21
Please also take a look when you have time. @Demogorgon314 @aloyszhang 

I think it's likely to be caused by the failure of `PersistentTopic#publishMessage` and potential retries in managed ledger. Also, there's a PR (https://github.com/apache/pulsar/pull/12018) that might fix the duplicated `BrokerEntryMetadata`.

**Comment by aloyszhang** [comment] 2021-11-02 03:48
> potential retries in managed ledger.

what is the exact behaviour here?

**Comment by BewareMyPower** [comment] 2021-11-02 03:55
> > potential retries in managed ledger.
> 
> what is the exact behaviour here?

See #12018 and `ManagedLedgerImpl#updateLedgersIdsComplete`. But I'm not sure whether it's the cause. Theoretically it shouldn't cause the duplicated `BrokerEntryMetadata` even before my fix.

**Comment by Raven888888** [comment] 2021-11-02 04:05
Possibly same Invalid unknonwn tag type: 6 error in #12455

**Comment by BewareMyPower** [comment] 2021-11-04 01:35
After confirming with @xiaotongwang1 , this issue could be fixed by #12018. So close it.

**Closed by BewareMyPower** 2021-11-04 01:35 UTC
Labels: type/bug
