### ISSUE TITLE
Every few days consumers stop receiving messages from some of the partitions when using key_shared

### ISSUE THREAD

**Issue by avimas** [apache/pulsar#7792] opened 2020-08-10 09:17 UTC
We have a very strange issue with partitioned topics and shared_key subscriptions, every few days no messages are being consumed from some of the partitions and the backlog keeps growing, the issue persists until we resubscribe or unloading the topic.
pulsar version is 2.6.0
you can see the issue in this screenshot partition 0 and 2 (most left and most right) are stuck, while partition 1 is consumed without any issues.

![image](https://user-images.githubusercontent.com/43335867/89767246-3727e380-db02-11ea-8ffa-5b7f598cc472.png)

I saw the following Exception in the brokers around the last consumed/acked time (edited) 
not sure if it's related, couldn't see any errors on the clients.

**2020-08-07T04:37:03.485 | java.lang.ArrayIndexOutOfBoundsException: null
04:37:03.484 [bookkeeper-ml-workers-OrderedExecutor-1-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught 
04:37:03.478 [pulsar-io-23-3] INFO  org.apache.pulsar.broker.service.ServerCnx - [/10.130.2.20:50286] Created subscription on topic persistent://internal/emsaas/enriched-event-unified-partition-0 / property-worker-cloud**

**Comment by codelipenghui** [comment] 2020-08-10 11:18
Thanks @avimas , Looks the problem is related to #7483 and it will release at 2.6.1 this week

**Comment by avimas** [comment] 2020-08-10 13:53
Thanks a lot!!

**Comment by sijie** [comment] 2020-08-12 08:23
Closed this issue since #7483 has fixed it. Please re-open it if 2.6.1 doesn't solve the problem.

**Closed by sijie** 2020-08-12 08:23 UTC
Labels: component/broker, triage/week-33, type/bug
