### ISSUE TITLE
[Bug] Pulsar Helm Charts are missing: https://pulsar.apache.org/charts/ returns 404

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#17799] opened 2022-09-22 09:24 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Any

### Minimal reproduce step

```
❯ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "apache" chart repository (https://pulsar.apache.org/charts):
	failed to fetch https://pulsar.apache.org/charts/index.yaml : 404 Not Found
Update Complete. ⎈Happy Helming!⎈
```

### What did you expect to see?

https://pulsar.apache.org/charts should contain Pulsar Helm Charts

### What did you see instead?

A 404 was returned

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment] 2022-09-22 09:24
@tisonkun can you help in resolving this? thanks

**Comment by tisonkun** [comment] 2022-09-22 09:35
@lhotari root cause located. Will push commits for this issue. Although, shall the helm chart be self-contained? Said depend on artifacts under its code repo.

**Comment by lhotari** [comment] 2022-09-22 09:40
> @lhotari root cause located. Will push commits for this issue. Although, shall the helm chart be self-contained? Said depend on artifacts under its code repo.

Thanks @tisonkun . I guess the location is where it is because of some legacy reasons: that's where it was published initially...

**Comment by tisonkun** [comment] 2022-09-22 09:47
@lhotari sure...

In any aspect we should keep the original file, but it would be reasonable to be self-contained.

**Comment by tisonkun** [comment] 2022-09-22 09:48
Perhaps change logics under https://github.com/apache/pulsar-helm-chart/blob/master/.ci/release.sh.

**Comment by tisonkun** [comment] 2022-09-22 09:52
Supposed the Helm Chart is part of the Apache release, perhaps upload the index.yaml to https://dist.apache.org/repos/dist/release/pulsar/.

**Comment by tisonkun** [comment] 2022-09-22 11:22
The issue reported here should be fixed now. Please confirm and close if it works.

**Closed** 2022-09-22 11:27 UTC
Labels: type/bug, website

**Comment by michaeljmarshall** [comment] 2022-09-23 02:44
> Supposed the Helm Chart is part of the Apache release. Perhaps upload the index.yaml file to https://dist.apache.org/repos/dist/release/pulsar/.

I started a thread on this back in June, but I wasn't able to find the time to update the release process. Here is a link to the thread: https://lists.apache.org/thread/2xmks3zzkh5cm4ghrqt4ys6zwh4c3gbj.

I agree that we should fix the release process. Updating where the `index.yaml` is stored will probably take a little time to change unless we can respond with an appropriate "moved" error to the helm client.
