### ISSUE TITLE
Dispatch messages to the new consumer after exist consumer acknowledged all dispatched messages in Key_Shared Subscription.

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#6554] opened 2020-03-19 02:25 UTC
Master issue #4077
**Is your feature request related to a problem? Please describe.**
Dispatch messages to the new consumer after exist consumer acknowledged all dispatched messages in Key_Shared Subscription.

**Comment by feeblefakie** [comment] 2020-03-31 05:29
Let me add a related issue and some discussion I and @codelipenghui had about this.

- [Key_Shared consumers with different subscriptions get messages for the same key in an inconsistent order](http://mail-archives.apache.org/mod_mbox/pulsar-users/202003.mbox/%3CCAPDOW74LN3WtdhpG_cgCCSg9MuMmkNV6giCGD5p%3DW1wWji0W7w%40mail.gmail.com%3E)
- https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1585527971073400

I think sticky consumers won't really solve it since consumers can be easily down in failure cases and it is pretty hard for applications to manage scalability of consumers.

**Comment by poulhenriksen** [comment] 2020-04-03 10:55
How come this is marked as a feature and not a bug?

It violates the ordering guarantee of Key_Shared, and basically makes Key_Shared useless if you dynamically add consumers.

I ask, because I would like to ensure this bug gets the proper attention, and is not regarded as a nice-to-have feature.

**Comment by feeblefakie** [comment] 2020-04-03 11:57
I totally agree with @poulhenriksen .

**Comment by feeblefakie** [comment] 2020-04-14 03:53
@codelipenghui Could you share updates on this if any ?   
Sorry for pushing, but I feel it is a really critical bug and Key_Shared users will have so much troubles if they just use it without doubt.

**Comment by codelipenghui** [comment] 2020-04-14 04:05
@feeblefakie We are already advancing this matter and I have drafted an approach. I will create a PIP soon.

**Comment by feeblefakie** [comment] 2020-04-14 04:59
@codelipenghui Thank you for sharing the update ! Good to know. :)

**Comment by merlimat** [comment] 2020-04-23 01:26
So, I think the problem here should be treated by having new consumers joining in a "paused" state. 

For example, consider this sequence:

 1. Subscriptions has `c1` and `c2` consumers
 2. `c3` joins. Some of the keys are now supposed to go to `c3`. 
 3. Instead of starting delivering to `c3`. We mark the current `readPosition` (let's call it `rp0_c3`) of the cursor for `c3`.
 4. Any message that now hashes to `c3` and that has `messageId >= rp0_c3` will be deferred for later re-delivery
 5. Any message that might get re-delivered (eg: originally sent to `c1`, but `c1` has failed) to `c3` and that has `messageId < rp0_c3` will be sent to `c3` 
 6. When the `markDelete` position of the cursor will move past `rp0_c3` the restriction on `c3` will be lifted. 

Essentially, `c3` joins but can only receive old messages, until everything that was read before joining gets acked.

**Comment by feeblefakie** [comment] 2020-04-23 03:41
@merlimat 
I'm not fully sure about the solution but does it guarantee key ordering ?
For example, a message X with key "A" is first consumed in `c1`, and another message Y with key "A" can possibly go to `c3` ? (can we make sure message X is consumed and acked before message Y ?)

**Comment by merlimat** [comment] 2020-04-23 04:21
> For example, a message X with key "A" is first consumed in c1, and another message Y with key "A" can possibly go to c3 ? (can we make sure message X is consumed and acked before message Y ?)

Yes, the above proposal takes care of that. 

The important point is that X could be re-sent to `c3`, in case `c1` fails just after `c3` has joined.

**Comment by codelipenghui** [comment] 2020-04-23 06:07
@merlimat I like the approach you have mentioned.

**Comment by codelipenghui** [comment] 2020-05-19 02:05
@pouledodue @feeblefakie @merlimat  I have pushed a PR #6799 for this issue. Please help review, thanks.

**Comment by codelipenghui** [comment] 2020-06-16 05:42
Reopen it via https://github.com/apache/pulsar/issues/5819#issuecomment-644510797.

**Comment by rocketraman** [comment] 2020-07-02 21:21
PR #7106 referred to by https://github.com/apache/pulsar/issues/5819#issuecomment-644543109 is marked as closed and merged, with milestone 2.6.0. Should this issue be closed with 2.6.0 milestone after all?

**Comment by codelipenghui** [comment] 2020-07-03 00:40
@rocketraman As discussed with @feeblefakie in slack channel, looks there are some problems with auto split mechanism. So I reopen this issue for tracking this problem. And @feeblefakie has verified consistent hash mechanism is work as expected. I will take a look at the auto split mechanism later.

**Comment by feeblefakie** [comment] 2020-07-03 01:08
@codelipenghui Should I create a open issue for [this](https://github.com/apache/pulsar/issues/5819#issuecomment-644510797) ?
I realized that I just created how to reproduce doc in my repo and shared it in only the closed issue.

**Comment by codelipenghui** [comment] 2020-07-03 11:24
@feeblefakie Yes, thanks.

**Comment by feeblefakie** [comment] 2020-07-06 00:24
@codelipenghui #7455  PTAL.

**Comment by wolfstudy** [comment] 2020-08-14 17:13
The issue will be tracked in #7455 so move the issue to release/2.6.2

**Comment by wolfstudy** [comment] 2020-10-31 03:00
It seems that #8292 has solved this problem, let us consider closing this issue.

**Closed by wolfstudy** 2020-10-31 03:00 UTC
Labels: component/broker, release/2.6.2, triage/week-13, type/bug
