### ISSUE TITLE
Key_Shared subcription not working correctly

### ISSUE THREAD

**Issue by MonicaMagoniCom** [apache/pulsar#9699] opened 2021-02-24 15:01 UTC
We are using Pulsar in our cloud environment (deployed with Kubernetes).
Pulsar is configured in **key_shared** mode subscription and it happens that when the traffic is higher than usual (in our case,  Pulsar suddendly receives 300 messages), messages which have the same key are mapped to a different consumer. 
This lasts for the duration of the traffic peak, then the situation is restored and the messages with the same key are normally deliver to their right consumer. In our environment this causes an Optimistic Lock Exception, since 2 messages with the same key arrives at 2 different consumers, and they both try to update the same document in MongoDB. 

**To Reproduce**
Pulsar 2.6.2
Key_shared mode 
Sudden peak of traffic 

**Expected behavior**
I expect that messages with the same key are delivered to the same consumer, also when traffic increases.

**Comment by MarvinCai** [comment] 2021-02-24 23:58
hi, what to confirm is any consumer added during the peak? 
Cause if new consumer is added default behavior will cause rehash and message with same key can then be sent to different consumer.

**Comment by MonicaMagoniCom** [comment] 2021-02-25 07:33
@MarvinCai Hi, actually not, we are not creating any new consumer during the peak. That's why I do not expect any reshashing process to be performed.

**Comment by ilpanich** [comment] 2021-03-02 08:47
Hi @MarvinCai.
Any news about this issue?

**Comment by asadsalman** [comment] 2021-03-02 08:53
Hi!
I'm new to the Pulsar project and trying to take this up as my first issue. I tried to reproduce this issue by writing a simple producer/consumer in standalone mode with Key_Shared subscription but wasn't able to reproduce the issue.

I had to the producer produce 1000+ messages with the same key as quickly as possible, but they all end up at the same consumer (I ran 2-4 consumers).

I'm happy to push my PoC project to a repo in the morning, maybe OP or someone else can help me reproduce the issue.

**Comment by ilpanich** [comment] 2021-03-02 09:05
Just to help you to reproduce: we have 3 producer enqueing messages on the same queue.
Messages are then pull in batch mode by 3 consumer performing some actions for each message and saves data on a DB (thus raising an optimitic lock exception, which means that more than one consumer is working on two different messages related to the same key).
We reach the issue even with less than 1000 messages.
Hope this can help to reproduce the issue.

**Comment by asadsalman** [comment] 2021-03-02 09:25
Ah okay, thanks for the additional details. I only had one producer and I didn't add batching. I'll try with that.

Moreover, were the messages persistent or non-persistent? I don't know if it makes a difference, just trying to match your setup as closely as possible.

**Comment by ilpanich** [comment] 2021-03-02 09:44
Thank you.
We use persistent messages currently, we noticed the issue with them.

**Comment by codelipenghui** [comment] 2021-03-02 16:11
@ilpanich If you want to enable producer batching and want to consume by the key_shared subscription, you can set the `batcherBuilder(BatcherBuilder.KEY_BASED)`. So that the producer will combine messages of the same key in a batch to send.

**Comment by ilpanich** [comment] 2021-03-02 16:17
Hi @codelipenghui.
Is your suggestion to enable producer batching mandatory in order to consume batch?
We are only using batch consumers, our producers still work in standard mode.

**Comment by codelipenghui** [comment] 2021-03-03 04:18
@ilpanich The producer enabled the default batch policy based on the time(1ms for a batch), so this will lead to the messages with different keys add to one batch and send to the broker. So after the batch dispatched to the consumer, the consumer might receive the different keys of the batch.

There are 2 options to get it to work

1. Disable the message batching on the producer side
2. Use the KEY_BASE batching on the producer side, since the batch message of the KEY_BASED batcher only contains the messages with the same key.

**Comment by ilpanich** [comment] 2021-03-03 08:24
@codelipenghui There is a misunderstanding.
As I stated above, we use batching only on consumers, there is no batching enabled on the producers side.
So I suppose we already use option 1.
The consumers still receive messages from different keys in the batch only during the peak.

**Comment by codelipenghui** [comment] 2021-03-03 15:07
@ilpanich The producer enabled the batching by default. You can print the message ID that the consumer received to check if the message is a batch message. If it is a batch message, you will see the batch index, if not, the batch index will always -1.

**Comment by ilpanich** [comment] 2021-04-28 08:47
Hi @codelipenghui, we have checked and resolved as you suggested.
You can close this issue, there are no further actions needed.
Thank you for your support..

**Closed** 2021-04-28 08:48 UTC
Labels: type/bug
