### ISSUE TITLE
Failed to enable State API in K8s installation

### ISSUE THREAD

**Issue by pedro93** [apache/pulsar#5687] opened 2019-11-18 15:53 UTC
**Describe the bug**
Can't enable State API in a minikube-based installation of Pulsar, despite adding the appropriate property `extraServerComponents` to the values-mini.yaml in the bookkeeper.configData section.

**To Reproduce**
1. Add the following line to values-mini.yaml under the bookkeeper.configData section:
```yaml
extraServerComponents: "org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent"
```
2. Launch pulsar cluster via helm (this is using the helm templates found in this repo):
```
helm install . --values values-mini.yaml helm -n pulsar
```
3. When the K8s cluster is ready, check the configuration of the bookkeeper nodes and confirm that the `extraServerComponents` property in `conf/bookkeeper.conf` is not defined with the specified value.

**Expected behavior**
That following the steps to reproduce the bookkeeper nodes would have this property defined.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Minikube (v1.4.0) deployment
 - Pulsar version v2.4.1

**Additional context**
I believe this issue is due to https://github.com/apache/pulsar/commits/master/docker/pulsar/scripts/apply-config-from-env.py which ignores commented lines, as such to fix this issue, the extraServerComponents property should not be commented but defined with a default empty value. 

This issue is not limited to the aforementioned property only but to all properties that are commented out, as the setup/procedure to enable such features are not working for K8s deployments.

**Comment by jiazhai** [comment] 2019-11-21 03:43
Thanks @pedro93 for reporting this. :) since you have already root caused this issue, would you like to provide a fix for this?

**Comment by pedro93** [comment] 2019-11-21 08:55
Hello @jiazhai I can try to provide a fix. 

Do you confirm that this is indeed a bug and not some misconfiguration on my part?

As to the fix, I’ve tried locally to uncomment said property in the bookkeeper.conf file and build the project but the built docker images when run still have the property commented. Any idea why?

**Comment by jiazhai** [comment] 2019-12-02 12:32
@pedro93,  Thanks for the clarification.  and sorry for the delay.
`apply-config-from-env.py` will use the env vars, which passed into docker, to replace the config file(no mater the value is setting or not in the file). so your change to `deployment/terraform-ansible/templates/bookkeeper.conf` or `conf/bookkeeper.conf` will not take effect. 
In your example, the value in `values-mini.yaml` will take effect. 

Seems , in your example:
```extraServerComponents: "org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent"
```
These *\" \"* are not needed?

**Comment by jiazhai** [comment] 2019-12-02 13:54
@wolfstudy to fix this issue.  This is a bug in apply-config-from-env.py

**Closed** 2019-12-06 10:07 UTC
Labels: help wanted, triage/week-46, type/bug
