### ISSUE TITLE
[Bug] JavaDoc (generated?) has Chinese text in it (as appears in Intellij)

### ISSUE THREAD

**Issue by dlg99** [apache/pulsar#20234] opened 2023-05-05 18:19 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.3, didn't check others

### Minimal reproduce step

Intellij, mouse over SinkContext to see context JavaDoc

### What did you expect to see?

English JavaDoc

### What did you see instead?

<img width="473" alt="image" src="https://user-images.githubusercontent.com/8622884/236536237-73ecc605-589e-4e5c-a5e1-0712e3af362c.png">

### Anything else?

Does the language of the generated JavaDoc depend on Release manager's locale?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment] 2023-05-08 03:31
Cannot reproduce. It seems an IDE settings issue, especially the Chinese content is not API content but the display template.

**Comment by tisonkun** [comment] 2023-05-08 03:45
You may check https://www.jetbrains.com/help/idea/working-with-code-documentation.html#generate-javadoc about setting locales.

**Comment by tisonkun** [comment] 2023-05-08 11:59
Closing...

Invalid.

**Closed by tisonkun** 2023-05-08 11:59 UTC
Labels: type/bug
