### ISSUE TITLE
[docs] Add Go SerDe option

### ISSUE THREAD

**Issue by Jennifer88huang** [apache/pulsar#4752] opened 2019-07-18 04:20 UTC
**Is your feature request related to a problem? Please describe.**
Currently, Go does not have SerDe option. 

**Describe the solution you'd like**
We can add the option for Go, and complete the content in https://github.com/apache/pulsar/pull/4725.

**Comment by Jennifer88huang** [comment] 2019-07-18 04:20
@wolfstudy Could you please help add the option for Go? Thank you.

**Comment by wolfstudy** [comment] 2019-07-18 04:38
> @wolfstudy Could you please help add the option for Go? Thank you.

As sijie said, Go Function not support `SerDe`, so i have no way to add this content. 

In here, can we tell the user that Go Function does not support this feature for the time being? Or we remove this tab directly.

**Comment by sijie** [comment] 2019-11-25 22:30
@Jennifer88huang as we chatted before, we should consider adding those missing tabs. It is a way to tell user that this feature is not implemented. Otherwise people is confused about whether this feature is not implemented or not documented.

**Comment by Jennifer88huang** [comment] 2019-11-26 00:00
@sijie Got it.

**Comment by Jennifer88huang** [comment] 2019-11-27 10:19
@sijie #5750 can be finished before 12/3, maybe we can add this to 2.5.0.

**Comment by sijie** [comment] 2019-11-27 18:15
This issue is for adding Go SerDe documentation. #5750 is for adding notes indicating that the feature is not available in Go Functions. So we need to leave this issue open until we add SerDe to go function. Thus I remove milestone from this issue, but leave #5750 for 2.5.0. I will also remove "Fixes #4752" from the description of #5750, because we shouldn't close this issue when merging #5750

**Comment by Jennifer88huang** [comment] 2019-11-28 13:33
@sijie Got it.

**Comment by codelipenghui** [comment] 2020-05-19 06:00
@wolfstudy Could you please help double-check is the SerDe support in Go Functions?

**Comment by wolfstudy** [comment] 2020-05-20 17:05
> @wolfstudy Could you please help double-check is the SerDe support in Go Functions?

Currently, the SerDe not support in Go Functions

**Comment by Anonymitaet** [comment] 2020-05-28 08:51
Confirmed w/ long on 5/28, serde is still not available in Go.

**Comment by sijie** [comment] 2020-09-04 06:16
close this issue for now since serde is not supported in Go Function.

**Closed by sijie** 2020-09-04 06:16 UTC
Labels: component/documentation, component/functions, component/go, type/feature
