### ISSUE TITLE
Upgrade Debezium to a newer version

### ISSUE THREAD

**Issue by yeouchien** [apache/pulsar#8502] opened 2020-11-10 09:11 UTC
Pulsar currently use [1.0.0.Final](https://github.com/apache/pulsar/blob/0c9648b79ff92271536da07a884ec4854ca97027/pom.xml#L153) version of Debezium. 

This version of Debezium causes issue when using it with Postgres as describe in [here](https://gitter.im/debezium/user?at=5e3d21556f9d3d3498275d2f)

```
[debezium-postgresconnector-tiktok-change-event-source-coordinator] ERROR io.debezium.pipeline.ErrorHandler - Producer failure
java.lang.IllegalArgumentException: Invalid identifier:
        at io.debezium.relational.TableIdParser$TableIdTokenizer.tokenize(TableIdParser.java:68) ~[debezium-core-1.0.0.Final.jar:1.0.0.Final]
        at io.debezium.text.TokenStream.start(TokenStream.java:447) ~[debezium-core-1.0.0.Final.jar:1.0.0.Final]
        at io.debezium.relational.TableIdParser.parse(TableIdParser.java:28) ~[debezium-core-1.0.0.Final.jar:1.0.0.Final]
        at io.debezium.relational.TableId.parse(TableId.java:39) ~[debezium-core-1.0.0.Final.jar:1.0.0.Final]
        at io.debezium.connector.postgresql.PostgresSchema.parse(PostgresSchema.java:236) ~[debezium-connector-postgres-1.0.0.Final.jar:1.0.0.Final]
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.lambda$execute$0(PostgresStreamingChangeEventSource.java:133) ~[debezium-connector-postgres-1.0.0.Final.jar:1.0.0.Final]
        at io.debezium.connector.postgresql.connection.pgproto.PgProtoMessageDecoder.processMessage(PgProtoMessageDecoder.java:53) ~[debezium-connector-postgres-1.0.0.Final.jar:1.0.0.Final]
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.deserializeMessages(PostgresReplicationConnection.java:412) ~[debezium-connector-postgres-1.0.0.Final.jar:1.0.0.Final]
        at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.readPending(PostgresReplicationConnection.java:406) ~[debezium-connector-postgres-1.0.0.Final.jar:1.0.0.Final]
        at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.execute(PostgresStreamingChangeEventSource.java:119) ~[debezium-connector-postgres-1.0.0.Final.jar:1.0.0.Final]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:99) ~[debezium-core-1.0.0.Final.jar:1.0.0.Final]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by arumugamtp** [comment] 2020-11-12 17:36
I am trying to understand the problem here. Will update in few days. Thank you.

**Comment by hangc0276** [comment] 2020-11-14 00:38
@arumugamtp  Are you trying to fix it?

**Comment by lxcid** [comment] 2020-11-28 07:44
I think the issue is that debezium 1.0.0 final have a known connection bug with Postgres which is fix in the later version like 1.1.0.Beta1 or 1.0.1.Final. If we bump this version. It should resolve the issue.

**Comment by arumugamtp** [comment] 2020-12-02 04:53
@hangc0276  => Yup, I am trying to understand the issue and looking for a fix.

@lxcid => Thanks for the lead..

**Comment by lxcid** [comment] 2020-12-14 03:52
No problem! Hope to check back on this issue, any chance of dropping in next release?

**Comment by arumugamtp** [comment] 2020-12-25 07:06
@hangc0276 => please assign the issue to me.

**Comment by yeouchien** [comment] 2021-01-06 03:40
FYI there's a PR for this issue: https://github.com/apache/pulsar/pull/9036

**Comment by arumugamtp** [comment] 2021-01-07 04:24
Hi @yeouchien  => I reviewed the code changes of #9036, and looks good to me. Please assign this issue to code author. I will pick up another issue to work on. Thank you.

**Closed** 2021-08-13 23:34 UTC
Labels: type/enhancement, help wanted, triage/week-46
