### ISSUE TITLE
Need zero queue consumer to work with partitioned topics

### ISSUE THREAD

**Issue by mfsub** [apache/pulsar#7295] opened 2020-06-18 07:08 UTC
Currently, Zero queue consumer works only with non-partitioned topic. 
The suggested workaround from the pulsar team is to connect a zero queue consumer to individual partitions. 

Requesting to have support for zero queue consumer to work with partitioned topic as well.

**Comment by sijie** [comment] 2020-06-19 01:34
This is a duplicate of #7280

**Closed by sijie** 2020-06-19 01:34 UTC
Labels: type/feature
