### ISSUE TITLE
Incorrect behavior single Pulsar Client creating multiple consumers

### ISSUE THREAD

**Issue by jerrypeng** [apache/pulsar#4137] opened 2019-04-25 22:44 UTC
**Describe the bug**

After the introduction https://github.com/apache/pulsar/pull/3312 where the pulsar client try to return the same consumer on multiple consumer creates, incorrect and unexpected consumer creation behavior can occur.

If a single Pulsar client creates multiple consumers, some of the consumers retuned will be the the same consumer.  

This is not the expected behavior, since if I try to create N consumers for a topic, I somehow get less consumers.  This really gets to be a issue, in multi-thread applications in which different threads might create multiple instances of consumers at or near the same time.  I will get fewer actual consumers than requested.  Some threads will get new consumers while others might get the same consumer.

What I described above is what is happening for running Pulsar Functions in threaded mode.  When I create/update/delete functions, this situation can occur and some functions instances doesn't get a valid consumer.

For example I have 5 instances of a function and I print out the consumer that is created for each of them

```
# instance 0
13:27:56,971 INFO [public/default/generator-function-0] [instance: 0] PulsarSource - consumer: ConsumerBase{subscription='public/default/generator-function', consumerName='d2505', topic='persistent://public/default/jerry-input'} - Object Id: 1083103426


# instance 1
13:27:56,971 INFO [public/default/generator-function-1] [instance: 1] PulsarSource - consumer: ConsumerBase{subscription='public/default/generator-function', consumerName='d2505', topic='persistent://public/default/jerry-input'} - Object Id: 1083103426

#instance 2
13:27:56,896 INFO [public/default/generator-function-2] [instance: 2] PulsarSource - consumer: ConsumerBase{subscription='public/default/generator-function', consumerName='61f68', topic='persistent://public/default/jerry-input'} - Object Id: 1143398780

#instance 3
13:27:56,915 INFO [public/default/generator-function-3] [instance: 3] PulsarSource - consumer: ConsumerBase{subscription='public/default/generator-function', consumerName='d2505', topic='persistent://public/default/jerry-input'} -  Object Id: 1083103426

#instance 4
13:27:56,896 INFO [public/default/generator-function-4] [instance: 4] PulsarSource - consumer: ConsumerBase{subscription='public/default/generator-function', consumerName='d2505', topic='persistent://public/default/jerry-input'} -  Object Id: 1083103426
```

As you can see from the printed ```Object Id```, some of the function instances get retuned the same consumer object.

When I do topic stats on the input topic:

```
$ ./bin/pulsar-admin topics stats jerry-input
{
  "msgRateIn" : 0.0,
  "msgThroughputIn" : 0.0,
  "msgRateOut" : 0.0,
  "msgThroughputOut" : 0.0,
  "averageMsgSize" : 0.0,
  "storageSize" : 0,
  "publishers" : [ ],
  "subscriptions" : {
    "public/default/generator-function" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 0,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "unackedMessages" : 0,
      "type" : "Shared",
      "msgRateExpired" : 0.0,
      "consumers" : [ {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "61f68",
        "availablePermits" : 1000,
        "unackedMessages" : 0,
        "blockedConsumerOnUnackedMsgs" : false,
        "metadata" : {
          "instance_id" : "2",
          "application" : "pulsar-function",
          "id" : "public/default/generator-function"
        },
        "address" : "/127.0.0.1:64784",
        "connectedSince" : "2019-04-25T13:27:56.892-07:00",
        "clientVersion" : "2.4.0-SNAPSHOT"
      }, {
        "msgRateOut" : 0.0,
        "msgThroughputOut" : 0.0,
        "msgRateRedeliver" : 0.0,
        "consumerName" : "d2505",
        "availablePermits" : 1000,
        "unackedMessages" : 0,
        "blockedConsumerOnUnackedMsgs" : false,
        "metadata" : {
          "instance_id" : "4",
          "application" : "pulsar-function",
          "id" : "public/default/generator-function"
        },
        "address" : "/127.0.0.1:64784",
        "connectedSince" : "2019-04-25T13:27:56.892-07:00",
        "clientVersion" : "2.4.0-SNAPSHOT"
      } ]
    }
  },
  "replication" : { },
  "deduplicationStatus" : "Disabled"
}

```

Only 2 out of the 5 instances' consumers gets connected because 3 of the instances all have the same consumer object.

This creates big issues for functions.  In the worse case, I can have a function of N instances and only one of the instances gets data which I have observed happen personally.

I propose we roll back these changes in the pulsar client.

Perhaps @sijie @jiazhai @lovelle can comment since you guys implemented/approved the PRs related to this feature

### How to recreate

1. Configure functions to run in ThreadRuntime
2. Submit function with multiple instances
3. Check topics stats for number consumers
4. Repeat above steps a couple of times and eventually you will see that the number of consumer for the topic be less the the number of instances for the function

I have also recreated the issue by only using pulsar client and consumer:

https://gist.github.com/jerrypeng/dba515c9748849dd4d51c2b5dbd865ed

**Comment by jerrypeng** [comment] 2019-04-25 22:47
@merlimat can you comment as well

**Comment by merlimat** [comment] 2019-04-25 22:55
I think that the original PR kind of broke the semantic of the API (`newConsumer()` returning an actual consumer) and that causes the problems like in functions when running in thread runtime. That would probably be affecting other applications as well. 

Other than that, I think there would be a problem coming with unacked messages. 
 1. Consumer-1 gets M1
 2. Consumer-2 shares the same underlying "consumer"
 3. Closing Consumer-1 *will not* close the underlying consumer
 4. M1 will not be replayed to Consumer-2 as it was the case before the change.

**Comment by lovelle** [comment] 2019-04-26 00:03
First of all, my apologise for the trouble. Please, let me clarify when this is happening.

A previously built consumer would be returned when the next union is met: Shared mode consumers on the same topic with the same subscription within the same pulsar client.

Previously to #3312 creating a new consumer with the previous mentioned characteristics would result in a waste of resource and wouldn't result in a truly more threaded consumer, if performance is wanted, I think the asynchronous api should be good enough.

Even so, if the same consumer is wanted to be created with this characteristics, in order to have truly more threaded consumer, you could do it with a new pulsar client instance provided.

> Other than that, I think there would be a problem coming with unacked messages.

Let me try to answer this with your example:

  1. Consumer-1 gets Message-1.
  2. Consumer-2 is created but Consumer-1 is returned.
  3. Consumer-1 receive close(), but won't close the consumer in fact.
  4. Consumer-2 is still alive, and any redelivery will still be made.
  5. Consumer-2 receive close(), this time really closing the consumer.

The key here is that Consumer-2 actually never exists, all the time was the same Consumer-1 doing the work.
Anyway, if you like, I can add a test in order to assert this scenario and verify this for real.

Keep in mind that if we revert #3312 the issue #3226 will come again to the surface.

**Comment by sijie** [comment] 2019-04-26 00:06
I think #3743 was attempting to revert to the change and #3746 comes up a fix with reference counting. If reverting, we need to revert all related changes. So I would suggest holding a bit on reverting. Let’s discuss it to see if there is any other fixes. If there is no, I am fine with reverting all the changes.

For the issue that functions is facing, I think it comes from MessageListener. Because if consumers are using receive and receiveAsync, the messages should be spreading across the instances calling the methods of a same consumer. So the fix for this issue can be:

1) add the support for multiple message listeners.

Or 

2) set the consumer name in functions.

Regarding the semantic question Matteo raises, I don’t know how to address his concern.

Regarding the unack redeliver behavior, the unacked messages will still be redeliverd to consumer-2 when ack time-out happens.

**Comment by merlimat** [comment] 2019-04-26 00:12
> Regarding the unack redeliver behavior, the unacked messages will still be redeliverd to consumer-2 when ack time-out happens.

That is only true if ack-timeout is enabled, but that is not the default behavior (because we cannot establish a "default" max processing time).

In the default case, the message received by application will stay unacked.

**Comment by sijie** [comment] 2019-04-26 00:13
Alternatively we can return a wrapper consumer of the reference counted consumer. Although I am not sure if there are any problems around this approach.

**Comment by sijie** [comment] 2019-04-26 00:15
> That is only true if ack-timeout is enabled, but that is not the default behavior (because we cannot establish a "default" max processing time).

That’s true.

**Comment by lovelle** [comment] 2019-04-26 00:18
idk if is a good solution but unsubscribe() instead of close() would finish the consumer on the first try.

**Comment by jerrypeng** [comment] 2019-04-26 00:27
@sijie in regards to how this impacts functions, even if we change PulsarSource to call receive() or add multiple message listener support , it still causes nondeterministic behavior when creating functions using ThreadRuntime.  Multiple attempts at creating the same function with the same number of instances will yield different number of consumers.  This creates a nightmare when trying to debug functions

**Comment by sijie** [comment] 2019-04-26 00:39
@jerrypeng for functions, does it make better to set a consumer name (e.g. instance-<instance-if>-consumer) for both debugging and addressing the problem? Hence at broker side, if you are using stats, you know which consumer has problem. At client side, it should have returned a brand new consumer instance if a different consumer name is used. I forgot if current code can do that or not. If not, maybe that’s a simple fix to go first with setting a unique consumer name in functions.

**Comment by jerrypeng** [comment] 2019-04-26 00:48
@sijie I just tested with consumers with consumer name set as UUIDs, yet they still get returned as the same instance.  Though that just maybe be a bug. 

We currently do set consumer meta data to indicate which function and instance this consumer is from which should be enough info for debugging purposes.

**Comment by srkukarni** [comment] 2019-04-26 00:50
+1 to adding consumer name to resolve the functions issue.
As for the optimization issue, I think it breaks the newConsumer() abstraction in a fundamental way.

**Comment by lovelle** [comment] 2019-04-26 01:00
subscription name instead of consumer name was added in order to identify duplicated consumers.

> I think it breaks the newConsumer() abstraction in a fundamental way.

It breaks in the same way a singleton class does, and anyway it's used extensively in a lot of places.

**Comment by jerrypeng** [comment] 2019-04-26 01:02
> subscription name instead of consumer name was added in order to identify duplicated consumers.

if that is the case, then there is no way for functions to side step this problem and we will have to revert the change because functions need to have to ability to create consumers using the same subscription

**Comment by lovelle** [comment] 2019-04-26 01:14
Isn't possible for functions just to share the consumer instance instead of create multiple of the same?

Also, maybe we can modify #3312 to use consumer name instead of subscription name, idk if we will break issue #3226 with that.

**Comment by lovelle** [comment] 2019-04-26 01:32
@jerrypeng I've just made #4139 in order to address what you need.

**Comment by lovelle** [comment] 2019-04-26 03:54
> In the default case, the message received by application will stay unacked.

Hence, maybe the feature we don't want is #3795?

**Comment by merlimat** [comment] 2019-04-26 05:05
> idk if is a good solution but unsubscribe() instead of close() would finish the consumer on the first try.

Unsubscribe is a different operation from close. It will actually remove the subscription and stop retaining data.

> for functions, does it make better to set a consumer name (e.g. instance--consumer) for both debugging and addressing the problem? 

@sijie Functions are already setting the consumer properties so they can be identified in the topic stats.

>> I think it breaks the newConsumer() abstraction in a fundamental way.

> It breaks in the same way a singleton class does, and anyway it's used extensively in a lot of places.

The problem is that the semantic of newConsumer() implies you're going to create a new "consumer" resource. If you're returning a cached object, the semantic is different. Application relying on the existing semantic will be broken.

> Isn't possible for functions just to share the consumer instance instead of create multiple of the same?

Functions with thread-runtime need to be able to manage the lifecycle of each consumer independently. This is a perfectly valid use of the API and was working correctly before. Similarly as functions, other application may be relying on the same API contract. 

> Hence, maybe the feature we don't want is #3795?

Without that, a consumer calling close() will cause all other consumers to stop receiving messages

**Comment by merlimat** [comment] 2019-04-26 05:17
I don't think that using the consumer name instead of the subscription name will solve the fundamental issue here. 

There are different problems: 
 1. Consumer name is randomly assigned if empty, so the caching will not take effect
 2. If application specifies same consumer name, then caching happen but: 
    a. Unacked messages will not be redelivered
    b. 1 or more consumers will be created, depending on race condition
    c. Consumer might actually have different configuration or metadata properties that are reported in topics stats
    d. There are issues with cached consumers using message listener (as the functions consumers are doing)

With all the downsides and the breaking of existing semantics, I don't see the need for consumers caching optimization. 

There is no problem is using multiple consumer from a same client instance. It does not impact performance or efficiency. 

If an application is requesting to create multiple consumers, that would be a valid use of the API. If an application has a bug and keeps creating new consumers, then the broker should protect itself and deny new consumers after a certain time.

**Comment by lovelle** [comment] 2019-04-26 12:31
> Without that, a consumer calling close() will cause all other consumers to stop receiving messages

And isn't that what is meant to be in this case?

> Consumer name is randomly assigned if empty, so the caching will not take effect

Yes, that's why at a first instance subscription name was chosen to verify duplicate consumers.

Agree with @Matteo that this optimizations maybe is not worth it just to fix issue #3226, maybe we can found a more easier solution to #3226 issue.

Since this optimizations seems to cause a lot of pain I made pull #4142 which reverts the entire feature and all related code to it, so you can decide the best path.

Apologies to all of you for the trouble.

**Comment by merlimat** [comment] 2019-04-26 16:06
>> Without that, a consumer calling close() will cause all other consumers to stop receiving messages

> And isn't that what is meant to be in this case?

But if you have 2 threads trying to use a consumer each: 
 1. T1 subscribes and gets C1
 2. T2 subscribes and gets C2
 3. If C1 == C2 (same instance)
     a. T1 closes C1
     b. T2 gets exception on the next receive()

Here each thread has the expectation that it gets a consumer and it will be valid until it gets explicitly closed.

**Comment by lovelle** [comment] 2019-04-26 16:18
Agree in that, but because of this ref count was implemented, I still don´t understand which use case within ref count on close() is broken. 

The user expecting the consumer to be closed but the consumer still retaining messages (default redelivery disabled) ?

**Closed** 2019-06-18 01:03 UTC
Labels: triage/week-20, type/bug
