### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by galrose** [apache/pulsar#10136] opened 2021-04-04 14:02 UTC
**Describe the bug**
I'm producing to a persistent topic in pulsar with no subscriptions. 
While producing the direct memory increases every time there is disk latency from the bookie's storage. 
I've stopped writing and the memory (in broker ) doesn't get released. It's been that way for a few days and I haven't found a solution. 

**To Reproduce**
1. Create pulsar cluster from the ansible play book (Either 2.7.0 or 2.7.1 I tried on both) 
2. Create a persistent topic (QW == QA == 3) 
3. Produce to the topic using pulsar perf
4. Wait for deletions or other actions that heavily affect the storage. 
5. Stop producing and the direct memory doesn't get released. 

**Expected behavior**
I expect the broker to release the memory. 
I don't understand why it increased every time there was throttling from the bookie in the first place and even if so, it should go back down when it successfully writes to all the bookies. 

**Desktop (please complete the following information):**
 - OS: Centos 7.8

**Additional context**
I've been struggling with this for a while and were trying to use pulsar as a central messaging platform for a large organization with multiple tenants. It would really help if there is a solution to this problem either in the configuration or if it's a bug then someone that understands could look at it.

**Comment by lhotari** [comment] 2021-04-29 11:33
Is this a duplicate of #9562 ?

**Comment by galrose** [comment] 2021-04-29 11:43
No because the maxMessageBufferSizeInMb is just the buffer for messages. Even after there is no producers and the all the data is in the bookie then the memory stays the same, instead of going back down.

**Comment by lhotari** [comment] 2021-04-29 11:43
For direct memory leaks, it's most likely about Netty pooled memory. For debugging the situation, it might be useful to check if there are log messages from the Netty leak detector.

The default setting for Netty leak detection for Pulsar broker is [SIMPLE](https://netty.io/4.1/api/io/netty/util/ResourceLeakDetector.Level.html#SIMPLE).

@galrose Can you check if you find this type of log messages: 

https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/ResourceLeakDetector.java#L318-L336

Please grep the logs for "LEAK: ".

**Comment by galrose** [comment] 2021-04-29 11:45
Thanks I'll try to do that :)

**Comment by lhotari** [comment] 2021-04-29 12:05
For example, In the k8s Helm chart deployment, an environment variable can be set for the broker by adding it under `broker.configData` in the `values.yaml` for the deployment.

```
broker:
  configData:
    PULSAR_EXTRA_OPTS: -Dpulsar.allocator.leak_detection=Simple
```

**Comment by lhotari** [comment] 2021-04-30 11:14
Since there's also a possibility that the reported problem could be related to Netty Recycler usage, I'd recommend doing the testing with Netty Recycler completely turned off. 

You can find positive reports about disabling the Netty Recycler at https://github.com/netty/netty/pull/5968#issuecomment-399578989 and https://github.com/netty/netty/pull/5968#issuecomment-352823429 . Elasticsearch [also disabled Netty Recycler completely](https://github.com/elastic/elasticsearch/blob/5baabff6670a8ed49297488ca8cac8ec12a2078d/distribution/tools/launchers/src/main/java/org/elasticsearch/tools/launchers/SystemJvmOptions.java#L50) because of the problems it causes. 

Here's an example of the recommended options to set in `PULSAR_EXTRA_OPTS`:
```
broker:
  configData:
    PULSAR_EXTRA_OPTS: -Dio.netty.recycler.maxCapacityPerThread=0 -Dpulsar.allocator.leak_detection=Simple -Dpulsar.allocator.exit_on_oom=true
```

It would be very useful if you could also share the possible impact to performance (throughput, latency, resource utilization) after disabling Netty Recycler with the setting described above.

**Closed** 2021-07-21 13:35 UTC
Labels: type/bug
