### ISSUE TITLE
Run `mvn clean install -DskipTests` command got exception

### ISSUE THREAD

**Issue by azhsmesos** [apache/pulsar#17311] opened 2022-08-27 15:16 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

无

### Exception stacktrace

<img width="1747" alt="image" src="https://user-images.githubusercontent.com/65518067/187036316-aa0b33c8-f664-4a70-ab24-8d40d71d0de8.png">

这个可能啥原因呀

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nicoloboschi** [comment] 2022-08-27 15:36
@azhsmesos please try to build from the root directory

**Comment by azhsmesos** [comment] 2022-08-28 05:17
> @azhsmesos please try to build from the root directory

谢谢 解决了，但是跑单侧时也会报错：
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/65518067/187058746-541a5adf-ec22-4e38-b78f-4301154b7192.png">
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/65518067/187058756-35400fd5-3613-42c7-b74b-3ad374e84e09.png">
麻烦帮忙看下可能啥原因呢

**Comment by tisonkun** [comment] 2022-08-28 09:11
@azhsmesos this can be relevant to https://github.com/apache/pulsar/issues/16694.

Please update the issue tile and content in English which is the default language to use. Also, these questions is not about `component/test` or `flaky-tests`. You'd better close it and ask in English on the [discussions forum](https://github.com/apache/pulsar/discussions/categories/q-a) or in Chinese on a [third-party hosted forum](https://forum.streamnative.io/c/native/zh/22).

**Comment by nodece** [comment] 2022-08-29 02:41
The root cause is `broker.keystore.jks` not found, the Maven can copy this resource, but the IDEA cannot.

Please run the `mvn clean install -DskipTests=true` first, and then run your test.

**Closed** 2022-09-15 04:21 UTC
Labels: component/test, flaky-tests
