### ISSUE TITLE
NullPointerException On Send Message

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#2929] opened 2018-11-05 07:10 UTC
Instance already run more than 1 month, but today we got some error log:
```java
org.apache.pulsar.client.api.PulsarClientException: java.lang.NullPointerException
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:388)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:210)
	at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendAsync(PartitionedProducerImpl.java:167)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:78)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.send(TypedMessageBuilderImpl.java:54)
	at org.apache.pulsar.client.impl.ProducerBase.send(ProducerBase.java:50)
	at com.zhaopin.event.impl.EventImpl.pub(EventImpl.java:83)
	at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zhaopin.thrift.rpc.executor.DefaultThriftExecutor.doExecute(DefaultThriftExecutor.java:133)
	at com.zhaopin.thrift.rpc.executor.DefaultThriftExecutor$1.run(DefaultThriftExecutor.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
```
When restart the instance, no error log print anymore.
Client Version: 2.1.0-incubating

**Comment by aahmed-se** [comment] 2018-11-06 00:54
So this was a one time event ?

**Comment by codelipenghui** [comment] 2018-11-06 01:10
@aahmed-se No, it happens on a instance all the time until restart the instance.

**Comment by aahmed-se** [comment] 2018-11-06 01:14
lot's of changes and fixes in ProducerImpl.java in 2.2.0 so will to check to see if it's replicated there.

**Comment by merlimat** [comment] 2019-01-24 20:49
@codelipenghui any new occurrences of this problem with newer client lib? 

The problem is that it's difficult to see the "real" stack trace of the root cause exception since it's being stripped by Java (it stops printing the full stack trace after a while as an optimization).

**Comment by codelipenghui** [comment] 2019-01-25 03:42
@merlimat we can't reproduce this problem, it happened only once.

**Comment by merlimat** [comment] 2019-01-25 04:08
Ok if this happen any other time, please remember to scroll up into the logs to the first occourence of the exception, which should have the full stack trace

**Comment by ivankelly** [comment] 2019-01-28 21:23
Closing for now since we can't repro and there's not enough info to go on. Please open again if it happens again.

**Closed by ivankelly** 2019-01-28 21:23 UTC
Labels: triage/week-45, type/bug
