### ISSUE TITLE
Zookeeper in 3 node Kubernetes cluster does not pass heath check in 2.8.0

### ISSUE THREAD

**Issue by andrekramer1** [apache/pulsar#11070] opened 2021-06-24 08:47 UTC
**Describe the bug**
Running the Kubernetes Helm chart with a 2.8.0 pulsar image, Zookeeper pod 0 runs but fails repeatedly. The rest of the Pulsar cluster is waiting on Zookeeper initialization. The Zookeeper health check is not passing "echo ruok | nc localhost 2181" is not returning "imok" - just hanging I think. So the kubernetes health check is failing repeatedly. Zookeeper is also complaining about not resolving zookeeper-1 and zookeeper-2 as usual but the zookeeper-0 log have a new NullReferenceException that we've not seen before:

10:58:55.990 [epollEventLoopGroup-4-2] WARN  org.apache.zookeeper.server.NettyServerCnxnFactory - Exception caught
java.lang.NullPointerException: null
               at org.apache.zookeeper.server.NettyServerCnxnFactory$CnxnChannelHandler.channelActive(NettyServerCnxnFactory.java:258) ~[org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
               at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230) [io.netty-netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216) [io.netty-netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209) [io.netty-netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398) [io.netty-netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230) [io.netty-netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216) [io.netty-netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895) [io.netty-netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:522) [io.netty-netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) [io.netty-netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) [io.netty-netty-transport-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty-netty-common-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty-netty-common-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [io.netty-netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar:4.1.63.Final]
               at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty-netty-common-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.63.Final.jar:4.1.63.Final]
               at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.63.Final.jar:4.1.63.Final]
               at java.lang.Thread.run(Thread.java:829) [?:?

**To Reproduce**
Pulsar 2.8.0 docker image on Kubernetes as deployed by Helm chart. Changing just the zookeeper image to 2.7.0 and the cluster came up.

**Additional context**

Possibly java 11 is part of the problem or just a bad version of Zookeeper?

**Comment by mnit016** [comment] 2021-07-16 04:35
I've faced the same issue here when upgrade to 2.8, is any update?

**Comment by andrekramer1** [comment] 2021-07-19 07:22
A work around is using 2.7.x image for just Zookeeper.

**Comment by jmhublar** [comment] 2021-08-11 19:36
Yeah, this is not working at all.

**Comment by eolivelli** [comment] 2021-08-12 11:40
@hangc0276 I believe that we should fix this problem before cutting 2.8.1

**Comment by eolivelli** [comment] 2021-08-12 14:00
the NPE is here
https://github.com/apache/zookeeper/blob/00071dd3532f47c16e0973cc5af03cccec7ba9ab/zookeeper-server/src/main/java/org/apache/zookeeper/server/NettyServerCnxnFactory.java#L258

probably:
- there is another error in the logs
- the server is taking much time to come up

**Comment by hangc0276** [comment] 2021-08-12 14:15
Thanks for @eolivelli 's help, from the exception stack, i looks like something wrong in zookeeper or the helm chart. Would you please paste detail logs of zookeeper? @andrekramer1 @jmhublar @mnit016

**Comment by eolivelli** [comment] 2021-08-12 14:24
which helm chart are you using ?

the "official" Apache Pulsar Helm chart was never updated to Pulsar 2.8.0
see this PR that has not been merged
https://github.com/apache/pulsar-helm-chart/pull/130

**Comment by eolivelli** [comment] 2021-08-12 14:31
I am testing it now with my helm chart....stay tuned

**Comment by andrekramer1** [comment] 2021-08-13 13:38
Our chart does not have SSL enabled and I tried adding:
PULSAR_EXTRA_OPTS: >
      -Dzookeeper.ssl.hostnameVerification=false
      -Dzookeeper.ssl.quorum.hostnameVerification=false
But still failing on 3 node cluster. It's the same null reference exception. Possibly some startup race condition rather than SSL configuration?

**Comment by andrekramer1** [comment] 2021-08-13 13:47
I see the diff you point to above explicitly set Zookeeper to 2.7.2 until this issue here is fixed:

images:
  # bump to 2.8 after https://github.com/apache/bookkeeper/pull/2740 is fixed
  zookeeper:
    repository: apachepulsar/pulsar-all
    tag: 2.7.2
    pullPolicy: IfNotPresent
  bookie:
    repository: apachepulsar/pulsar-all
    tag: 2.7.2
    pullPolicy: IfNotPresent 

Possibly the chart you tested did the same?

**Comment by eolivelli** [comment] 2021-08-13 13:49
> Possibly the chart you tested did the same?
I used that Helm Chart by overriding the version of the docker image for all the components (zookeeper, broker, bookie...)
And I had verified that the version of ZK and Pulsar was good

**Comment by truonglenhut16111989** [comment] 2021-09-08 08:10
I faced the same issue when I tried with 2.8.0. Can this bug be fixed in branch 2.8?

**Comment by eolivelli** [comment] 2021-09-08 10:56
The problem is in the helm chart, not in Pulsar itself

**Comment by andrekramer1** [comment] 2021-09-08 12:15
@eolivelli when you say the problem is "in the helm chart" what exactly do you think is the issue? As far as I could tell it's a timing issue in start 3 Zookeepers when the cluster is created. It may work with 1 Zookeeper and the only smoking gun I saw was the Null reference exception in the zookeeper kubernetes pod logs. 2.8.0 uses Zookeeper 3.6.3 and won't start but using 2.7.0 which has Zookeeper 3.5.7 (only for Zookeeper pods) starts reliably.

**Comment by andrekramer1** [comment] 2021-10-06 15:05
Some further investigation found that the first Zookeeper created for the Kubernetes statefull set does not respond to the ready/liveness probe. This uses the "ruok" command and the reply from the server is to close the connection (as Zookeeper is not up and running). So the second and third replicas are never created. Somehow Zookeeper has stopped responding while initializing / creating a quorum. This can be confirmed by setting the enabled flag on Zookeeper ready and liveness probes to false in the helm chart. With probes disabled managed to initialize a 3 node cluster.

Created a debug branch of Zookeeper modified to respond to ruok and other client requests even when not fully initialized. With these changes it's also possible to bring up Zookeepers and Pulsar cluster with the probes enabled. The branch is here: https://github.com/andrekramer1/zookeeper/tree/early-ruok 

Would be possible to create a pull request from this but the implications of allowing client connections while Zookeeper is initializing would need to be considered. Hopefully the change list can help fix this issue.

**Comment by andrekramer1** [comment] 2021-10-06 16:20
@merlimat Yes, the fix I worked up is in the Netty server code. So probably would side step this with another server factory.

**Comment by lhotari** [comment] 2021-11-25 22:56
I created this fix for the Apache Pulsar Helm Chart: https://github.com/apache/pulsar-helm-chart/pull/180

**Comment by lhotari** [comment] 2021-11-25 23:04
Zookeeper issue is https://issues.apache.org/jira/browse/ZOOKEEPER-3988

**Comment by eolivelli** [comment] 2022-01-20 11:07
@andrekramer1 I created an alternative, more simpler PR that does not change the previous behaviour but fixes the NPE
[1798](https://github.com/apache/zookeeper/pull/1798).

Can you please take a look ?
is it enough to fix your problem ?
If the answer is "yes" that it is easier to commit the patch and see it released soon

**Comment by lhotari** [comment] 2022-01-26 13:06
@andrekramer1 do you have a chance to validate whether https://github.com/apache/pulsar-helm-chart/pull/214 changes would resolve the issue?

**Comment by andrekramer1** [comment] 2022-01-26 16:58
@lhotari sounds reasonable that it would help. Still running 1.16 for dev locally and the issue is being fixed in Zookeeper under: https://github.com/apache/zookeeper/pull/1800

**Closed** 2022-02-08 15:19 UTC
Labels: type/bug, release/blocker, component/zookeeper
