### ISSUE TITLE
Pulsar schema doesn't support null value

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#4803] opened 2019-07-25 06:21 UTC
**Describe the bug**

If a Pulsar producer sends messages without payload, Pulsar consumer is not able to consume the messages without payload. Because the payload passed to schema is an empty array not `null`. Hence exceptions are thrown. An example exception is shown as below:

```
org.apache.pulsar.client.api.SchemaSerializationException: Size of data received by BooleanSchema is not 1

	at org.apache.pulsar.client.impl.schema.BooleanSchema.validate(BooleanSchema.java:44)
	at org.apache.pulsar.client.impl.schema.BooleanSchema.decode(BooleanSchema.java:62)
	at org.apache.pulsar.client.impl.schema.BooleanSchema.decode(BooleanSchema.java:29)
	at org.apache.pulsar.client.impl.MessageImpl.getValue(MessageImpl.java:273)
	at org.apache.pulsar.client.impl.TopicMessageImpl.getValue(TopicMessageImpl.java:143)
```

**To Reproduce**

1. Use a typed producer to send messages without setting value.
2. Use a typed consumer to receive messages.

**Expected behavior**

The typed consumer should receive messages with a `null` value.

**Comment by sijie** [comment] 2019-07-25 06:22
In event-sourcing use cases, a `null` value is usually used for representing a delete operation. Hence we should return `null` if the message doesn't have any payload.

**Comment by jiazhai** [comment] 2019-08-20 06:01
move this into 2.5.0, since PR has already moved.

**Comment by fmiguelez** [comment] 2020-05-07 15:15
There is a workaround with direct consumer/reader interface since you can always verify if data is empty before calling getValue():

Message<GenericRecord> lastMsg = reader.readNext(); lastEntity = lastMsg.getData().length > 0 ? lastMsg.getValue() : null;

However there is not such option when working with functions. E.g. A Sink<GenericRecord> implementation will fail before calling write(Record<GenericRecord> record) if a message with no payload (valid tombstone) is received with this error:

10:02:27.911 [dbus/test/rtsink-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [dbus/test/rtsink:0] Uncaught exception in Java Instance
org.apache.pulsar.client.api.SchemaSerializationException: java.io.EOFException
at org.apache.pulsar.client.impl.schema.generic.GenericAvroReader.read(GenericAvroReader.java:80) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
at org.apache.pulsar.client.impl.schema.generic.GenericAvroReader.read(GenericAvroReader.java:42) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:36) ~[java-instance.jar:?]
at org.apache.pulsar.client.impl.schema.StructSchema.decode(StructSchema.java:100) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:96) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:39) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
at org.apache.pulsar.client.impl.MessageImpl.getValue(MessageImpl.java:276) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
at org.apache.pulsar.client.impl.TopicMessageImpl.getValue(TopicMessageImpl.java:143) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
at org.apache.pulsar.functions.source.PulsarRecord.getValue(PulsarRecord.java:74) ~[org.apache.pulsar-pulsar-functions-instance-2.5.1.jar:2.5.1]
at org.apache.pulsar.functions.instance.JavaInstanceRunnable.readInput(JavaInstanceRunnable.java:472) ~[org.apache.pulsar-pulsar-functions-instance-2.5.1.jar:?]
at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:246) [org.apache.pulsar-pulsar-functions-instance-2.5.1.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.io.EOFException
at org.apache.avro.io.BinaryDecoder.ensureBounds(BinaryDecoder.java:509) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.io.BinaryDecoder.readLong(BinaryDecoder.java:181) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.io.BinaryDecoder.readString(BinaryDecoder.java:279) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.io.ResolvingDecoder.readString(ResolvingDecoder.java:209) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:467) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:458) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:182) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:248) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:237) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:170) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:144) ~[org.apache.avro-avro-1.9.1.jar:1.9.1]
at org.apache.pulsar.client.impl.schema.generic.GenericAvroReader.read(GenericAvroReader.java:75) ~[org.apache.pulsar-pulsar-client-original-2.5.1.jar:2.5.1]
... 11 more
10:02:27.943 [dbus/test/rtsink-0] INFO org.apache.pulsar.functions.instance.JavaInstanceRunnable - Closing instance
10:02:27.964 [dbus/test/rtsink-0] INFO org.apache.pulsar.client.impl.ConsumerImpl - [persistent://dbus/test/dummy-objects] [dbus/test/rtsink] Closed consumer

**Closed** 2020-05-19 06:11 UTC
Labels: component/client, component/schemaregistry, triage/week-30, type/bug

**Comment by fmiguelez** [comment] 2020-06-29 08:09
The solution provided by solution #7139 to this BUG **does not work**.

- When trying to read a message with `null` value a `NullPointerException ` is thrown in other part of the code.

```
        msg = consumer.receive(timeoutMillis, TimeUnit.MILLISECONDS));

	java.lang.NullPointerException
		at org.apache.pulsar.client.impl.ConsumerStatsRecorderImpl.updateNumMsgsReceived(ConsumerStatsRecorderImpl.java:169)
		at org.apache.pulsar.client.impl.ConsumerImpl.messageProcessed(ConsumerImpl.java:1423)
		at org.apache.pulsar.client.impl.ConsumerImpl.internalReceive(ConsumerImpl.java:431)
		at org.apache.pulsar.client.impl.ConsumerBase.receive(ConsumerBase.java:175)
                ...
```
- It should not be required to explicitly indicate a `null `value to producer (only-key values should work just just fine). Exception thrown when working with implicit null value messages is `EOFException `in this case (the same before this a solution was provided).

I have created a test project to reproduce these issues (null values implicitly and explictly set with both schema and schemaless consumer): [pulsar-tombstone-test](https://github.com/fmiguelez/pulsar-tombstone-test)

**Comment by jiazhai** [comment] 2020-06-29 08:25
Thanks @fmiguelez for the test.
looks from the code, npe happens in stats path(ConsumerStatsRecorderImpl.java), would you like to provide a pull request to fix this issue:
```
    @Override
    public void updateNumMsgsReceived(Message<?> message) {
        if (message != null) {
            numMsgsReceived.increment();
            numBytesReceived.add(message.getData().length);        < === NPE
        }
    }

```

**Comment by fmiguelez** [comment] 2020-06-29 08:39
> Thanks @fmiguelez for the test.
> looks from the code, npe happens in stats path(ConsumerStatsRecorderImpl.java), would you like to provide a pull request to fix this issue:
> 
> ```
>     @Override
>     public void updateNumMsgsReceived(Message<?> message) {
>         if (message != null) {
>             numMsgsReceived.increment();
>             numBytesReceived.add(message.getData().length);        < === NPE
>         }
>     }
> ```

@jiazhai  I can do that but I think a more complete fix would be interesting as described in the test. E.g you need to explicitly set a `null` value to the produced message so the null checks kick in, IMHO `MsgMetadataBuilder.hasNullValue()` should be initialized to `true`.

Besides there are other issues with tombstones if no schema is used.

Would it be interesting to open a new BUG or reopen this one?

**Comment by jiazhai** [comment] 2020-06-30 01:47
Thanks @fmiguelez for the detailed explanation.  the proposal for the complete fix looks good to me, we need be careful for the backward compatibility if set default true for `MsgMetadataBuilder.hasNullValue()`. It would be better to open a new issue.
also @gaoran10 to take attention.

**Comment by fmiguelez** [comment] 2020-07-01 07:45
@gaoran10, @jiazhai I have opened a new ticket #7407 as indicated
