### ISSUE TITLE
[Doc] 

### ISSUE THREAD

**Issue by luweiqianyi** [apache/pulsar#18953] opened 2022-12-16 06:08 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

docker-compose.yaml in this url "https://pulsar.apache.org/docs/next/deploy-docker/#deploy-a-cluster-by-using-docker-composeyaml" cannot be deployed on docker. Maybe the format is error,please fix it!

### What is your suggestion?

Before offerring  some configure file on website,please do some test to make sure it works

### Any reference?

https://pulsar.apache.org/docs/next/deploy-docker/#deploy-a-cluster-by-using-docker-composeyaml

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment] 2022-12-18 02:35
Duplicate of #18952

**Closed by tisonkun** 2022-12-18 02:35 UTC
Labels: doc-required
