### ISSUE TITLE
Documentation of admin REST API is missing body parameters

### ISSUE THREAD

**Issue by jeremie-kaiko** [apache/pulsar#6625] opened 2020-03-27 10:20 UTC
**Describe the bug**
There seems to have a regression in the documentation #1650

There is still no body request in the current admin REST API

**To Reproduce**
1. Go to https://pulsar.apache.org/admin-rest-api/?version=2.5.0#operation/setMaxProducersPerTopic
2. There is no request body parameters

**Expected behavior**
To see request body parameters, that way we can use the REST API without looking at java source code :wink: 

**Screenshots**
![image](https://user-images.githubusercontent.com/59561696/77745981-7f93a880-701c-11ea-882e-ea7eaad2fea2.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04, firefox 74.0, chrome 80

**Comment by vzhikserg** [comment] 2020-06-02 21:58
@sijie This issue should be fixed by #7119.  Is it fine if it will be fixed in the next release (then this issue is fixed)? Or should we also update the swagger files for the previously released versions?

**Comment by vzhikserg** [comment] 2020-06-20 09:09
@sijie @jiazhai the issue is fixed by #7119 in 2.6.0. If you check https://pulsar.apache.org/admin-rest-api/?version=2.6.0#operation/setMaxProducersPerTopic you can see that all body parameters are in place

**Comment by sijie** [comment] 2020-06-29 01:45
Closed this issue since the issue has been fixed by #7119 in 2.6.0

@vzhikserg yeah if you can port the same change to the previous versions, that would be great!

**Closed by sijie** 2020-06-29 01:45 UTC
Labels: component/documentation, help wanted, triage/week-14, type/bug
