### ISSUE TITLE
ConcurrentModificationException occurs when dispatch message to consumers

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#7804] opened 2020-08-13 02:15 UTC
**Describe the bug**
```
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$SubList.checkForComodification(ArrayList.java:1241) ~[?:1.8.0_265]
	at java.util.ArrayList$SubList.size(ArrayList.java:1050) ~[?:1.8.0_265]
	at org.apache.pulsar.broker.service.Consumer.lambda$sendMessages$0(Consumer.java:267) ~[org.apache.pulsar-pulsar-broker-2.6.0-sn-12.jar:2.6.0-sn-12]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387) [io.netty-netty-transport-native-epoll-4.1.48.Final-linux-x86_64.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**To Reproduce**
It's hard to reproduce.

**Expected behavior**
Keep the list operation safely.

**Additional context**

**Comment by wolfstudy** [comment] 2020-10-31 03:06
Move this issue to 2.7.0.

**Comment by codelipenghui** [comment] 2020-11-17 02:16
move to milestone 2.8.0

**Comment by zymap** [comment] 2021-03-02 02:39
Move this to the next release.

**Comment by congbobo184** [comment] 2021-07-26 14:15
Move this to the next release.

**Comment by michaeljmarshall** [comment] 2021-12-10 17:57
@codelipenghui - removing the 2.7.4 label. I'm not sure that we'll do a 2.7.5 release. We'll determine which branches to cherry pick to when this is completed/merged.

**Comment by tisonkun** [comment] 2022-12-09 13:26
Closed as stale. Please create a new issue if it's still relevant to the maintained versions.

The codebase has been changed a lot, and if we cannot reproduce the failure stably, leaving the issue open can starve.

**Closed by tisonkun** 2022-12-09 13:26 UTC
Labels: type/bug, help-wanted
