### ISSUE TITLE
Improve read performance for tiered-storage segment readout

### ISSUE THREAD

**Issue by jiazhai** [apache/pulsar#4025] opened 2019-04-11 04:07 UTC
As discussed in slack channel with @chairmank , Steve suggested that we could do a read-ahead to improve the read performance:

>I looked at `BlobStoreBackedInputStreamImpl` and `BlobStoreBackedReadHandleImpl` to understand how performance could be improved. I think that reads from blob store would be faster with speculative read-ahead, so that `refillBufferIfNeeded` can swap an already-populated buffer instead of blocking on a call to `blobStore.getBlob`.

**Comment by chairmank** [comment] 2019-04-11 12:50
possibly related: https://github.com/apache/pulsar/issues/3804

**Comment by sijie** [comment] 2019-11-04 05:35
Closed this since it is a duplicate of #3804

**Closed by sijie** 2019-11-04 05:35 UTC
Labels: component/tieredstorage, triage/week-16, type/feature, type/performance
