### ISSUE TITLE
[Bug] Bookkeeper crashed due to rocksdb

### ISSUE THREAD

**Issue by sindhushreem25** [apache/pulsar#23339] opened 2024-09-23 14:26 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

pulsar-2.10.6
bookie version-4.14.8

### Minimal reproduce step

none

### What did you expect to see?

none

### What did you see instead?

seeing the below error in bookie logs :
1726653435.650951721,"2024-09-18T09:57:15.650951721Z","#","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.650981683,"2024-09-18T09:57:15.650981683Z","# A fatal error has been detected by the Java Runtime Environment:","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.650992194,"2024-09-18T09:57:15.650992194Z","#","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.650998164,"2024-09-18T09:57:15.650998164Z","#  SIGSEGV (0xb) at pc=0x00007feaedff3dac, pid=1, tid=375","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.651002955,"2024-09-18T09:57:15.651002955Z","#","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.651007965,"2024-09-18T09:57:15.651007965Z","# JRE version: OpenJDK Runtime Environment Zulu17.52+17-CA (17.0.12+7) (build 17.0.12+7-LTS)","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.651014265,"2024-09-18T09:57:15.651014265Z","# Java VM: OpenJDK 64-Bit Server VM Zulu17.52+17-CA (17.0.12+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.651019285,"2024-09-18T09:57:15.651019285Z","# Problematic frame:","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.651233908,"2024-09-18T09:57:15.651233908Z","# C  [librocksdbjni11420926655858880589.so+0x3f3dac]  rocksdb::DBImpl::WriteImpl(rocksdb::WriteOptions const&, rocksdb::WriteBatch*, rocksdb::WriteCallback*, unsigned long*, unsigned long, bool, unsigned long*, unsigned long, rocksdb::PreReleaseCallback*)+0x14bc","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.651241509,"2024-09-18T09:57:15.651241509Z","#","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.651247449,"2024-09-18T09:57:15.651247449Z","# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /pulsar/core.1)","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.651252099,"2024-09-18T09:57:15.651252099Z","#","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.651438120,"2024-09-18T09:57:15.65143812Z","# An error report file with more information is saved as:","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.651449361,"2024-09-18T09:57:15.651449361Z","# /pulsar/hs_err_pid1.log","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.862360422,"2024-09-18T09:57:15.862360422Z","#","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.862398625,"2024-09-18T09:57:15.862398625Z","# If you would like to submit a bug report, please visit:","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.862405155,"2024-09-18T09:57:15.862405155Z","#   http://www.azul.com/support/","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.862410195,"2024-09-18T09:57:15.862410195Z","# The crash happened outside the Java Virtual Machine in native code.","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.862414806,"2024-09-18T09:57:15.862414806Z","# See problematic frame for where to report the bug.","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.862419226,"2024-09-18T09:57:15.862419226Z","#","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.862423526,"2024-09-18T09:57:15.862423526Z","","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.862428486,"2024-09-18T09:57:15.862428486Z","[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007feb6d9ce6ec]","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper","x.x.x.x"
1726653435.862432656,"2024-09-18T09:57:15.862432656Z","","itomdipulsar-bookkeeper-2","namespace","itomdipulsar-bookkeeper",""

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment] 2024-09-23 14:46
> pulsar-2.10.6
> bookie version-4.14.8

These aren't supported versions. I'm closing this issue since in the OSS project we only support Pulsar 3.0.x and Pulsar 3.3.x at the moment. Please upgrade your version and if the problem reproduces, open a new issue.

**Closed by lhotari** 2024-09-23 14:46 UTC
Labels: type/bug
