### ISSUE TITLE
NPE occur when get partitioned topic stats

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#5505] opened 2019-10-30 13:43 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/12592133/67863080-2eab8100-fb5e-11e9-8621-0c07c388757d.png)

**Pulsar version**
2.4.1

**Comment by Jennifer88huang** [comment] 2019-10-31 02:18
@codelipenghui Thank you for raising the issue. Do you know the reason of this issue, and could you fix it?

**Comment by codelipenghui** [comment] 2019-10-31 03:16
@Jennifer88huang I will take a look this issue later

**Comment by Jennifer88huang** [comment] 2019-10-31 05:53
@codelipenghui Thank you.

**Comment by yjshen** [comment] 2019-12-15 10:38
@codelipenghui does this bug still exists? how could I reproduce it?

**Comment by codelipenghui** [comment] 2019-12-15 10:58
@yjshen Yes, i think it have not fixed and i have not reproduce it yet.

**Comment by sijie** [comment] 2020-01-14 12:35
@codelipenghui I am closing this issue for now. if you have reproduced the behavior, please re-open the task.

**Closed by sijie** 2020-01-14 12:35 UTC
Labels: type/bug
