### ISSUE TITLE
delayed message other than delivered right away

### ISSUE THREAD

**Issue by DongbinNie** [apache/pulsar#133] opened 2016-12-02 06:50 UTC
Delayed message, it's better to can have different delayed time for subscriptions on the same topic.

[merlimat]
This one is interesting. I'd like to see how is feasible to do it in a highly scalable way. Perhaps this might be a good candidate to be implemented as a recipe (a ready-made solution built on top of the client library), rather than directly in the server.

[DongbinNie]
Agree, it can be implemented in the client side to alleviate server's burden.

**Comment by merlimat** [comment] 2016-12-03 00:40
Other than just delaying the message delivery, I think we could also provide a more general use distributed event scheduler, that can be implemented with multiple cascading queues.

**Comment by DongbinNie** [comment] 2016-12-03 14:03
@merlimat could you please give a detailed description of the solution "multiple cascading queues", thanks.

**Comment by XiaoZYang** [comment] 2018-05-25 15:59
Cool, that sounds interesting !

**Comment by ivankelly** [comment] 2018-08-30 15:12
@merlimat did anything ever happen with this?

**Comment by ivankelly** [comment] 2018-12-05 22:21
Closing as duplicate of #2375

**Closed by ivankelly** 2018-12-05 22:21 UTC
Labels: type/feature
