### ISSUE TITLE
[Feature Request] Dynamically refresh client after updating the number of partitions when the routing mode is not key hash

### ISSUE THREAD

**Issue by JevonQ** [apache/pulsar#3454] opened 2019-01-27 15:52 UTC
According to the web page (admin-api-partitioned-topics, https://pulsar.apache.org/docs/en/admin-api-partitioned-topics/), when admin increases the number of partitions on an existing partitioned topic, the newly created partition will not be seen until the producers/consumers are recreated. I think the way is not friendly for the users.

I understand that the requirement is needed for key hash routing mode because increasing/decreasing the partition number can violate partition ordering. But I don't think it is mandatory for round-robin/single default mode. So I'm proposing to recreate producers/consumers within the pulsar client and make the whole process invisible to the application when the admin changes the partition number when the routing mode is not key hash. Besides, the deletion on the partition could also be allowed.

**Comment by jiazhai** [comment] 2019-01-28 03:10
#3230 is related

**Comment by ivankelly** [comment] 2019-02-07 09:39
Marking this as a dupe of #3230 , so we can track this in a single place.

**Closed by ivankelly** 2019-02-07 09:39 UTC
Labels: component/client, type/feature
