### ISSUE TITLE
When function is created, the CPU  of the functions worker node will rise rapidly

### ISSUE THREAD

**Issue by xuesong172500** [apache/pulsar#7812] opened 2020-08-13 10:47 UTC
**Describe the bug**
pulsar 2.5.2

![image](https://user-images.githubusercontent.com/54351417/90125727-14612d80-dd95-11ea-96b0-4f0eba13e6da.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sijie** [comment] 2020-08-14 02:04
@xuesong172500 Can you share more details about this?

**Comment by xuesong172500** [comment] 2020-08-14 02:23
Create a function and you can reproduce it. Set 1 or 10 parallelism.

**Comment by wolfstudy** [comment] 2020-09-04 11:34
@xuesong172500 This is caused by too many jar packages. We can try to use a smaller tarball. Each time we use maven to build, we only place the corresponding module. We are also optimizing the logic. For the same jar package can be considered instead of reloading a jar for every function.

**Comment by xuesong172500** [comment] 2020-09-04 13:51
> @xuesong172500 This is caused by too many jar packages. We can try to use a smaller tarball. Each time we use maven to build, we only place the corresponding module. We are also optimizing the logic. For the same jar package can be considered instead of reloading a jar for every function.

@wolfstudy By reducing the size of jar package, we can reduce the CPU utilization to some extent.

**Comment by wolfstudy** [comment] 2020-09-07 01:22
cool @xuesong172500 , will close this issue

**Closed by wolfstudy** 2020-09-07 01:22 UTC
Labels: component/functions, triage/week-33, type/bug
