### ISSUE TITLE
[Bug] Java Pulsar Producer -  ProducerBuilder loadConf() throws RuntimeException when loading "maxPendingMessages" property from config map.

### ISSUE THREAD

**Issue by azmandzamiri** [apache/pulsar#17492] opened 2022-09-06 11:13 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Pulsar version: 2.10.1

### Minimal reproduce step

Add `maxPendingMessages` parameter into the config map and load the config. 

```java
                        HashMap<String, Object> pulsarProducerProperties = new HashMap<String, Object>();
                        pulsarProducerProperties.put("topicName", "my-topic");
                        pulsarProducerProperties.put("producerName", "my-producer");
                        pulsarProducerProperties.put("maxPendingMessages", 2000);
			pulsarProducer = pulsarClient.newProducer()
							.loadConf(pulsarProducerProperties)
							.create();
```

### What did you expect to see?

This seems to be a regression because this seems to be working in Pulsar 2.9.2 .

### What did you see instead?

A runtime exception is thrown by [`loadConf()` method](https://github.com/apache/pulsar/blob/656398e0c5663a9e96f77e040e7db724b3ad3aa3/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ConfigurationDataUtils.java#L69)

```
Exception: java.lang.RuntimeException: Failed to load config into existing configuration data
```

If the `maxPendingMessages` config is removed from the map , the Producer is created but the `masPendingMessages` value is `0` instead of the default value of`1000` as [documented](https://pulsar.apache.org/docs/client-libraries-java#configure-producer).

```
10:50:06.730 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ProducerStatsRecorderImpl - Starting Pulsar producer perf with config: {"topicName":"my-topic","producerName":"my-producer","sendTimeoutMs":30000,"blockIfQueueFull":false,"maxPendingMessages":0,"maxPendingMessagesAcrossPartitions":0,"messageRoutingMode":"RoundRobinPartition","hashingScheme":"JavaStringHash","cryptoFailureAction":"FAIL","batchingMaxPublishDelayMicros":1000,"batchingPartitionSwitchFrequencyByPublishDelay":10,"batchingMaxMessages":1000,"batchingMaxBytes":131072,"batchingEnabled":true,"chunkingEnabled":false,"compressionType":"NONE","initialSequenceId":null,"autoUpdatePartitions":true,"autoUpdatePartitionsIntervalSeconds":60,"multiSchema":true,"accessMode":"Shared","lazyStartPartitionedProducers":false,"properties":{},"initialSubscriptionName":null}
```

### Anything else?

Tried to use the PulsarBuilder API to set the maxPendingMessages and leave some other configuration in the config map (still using `loadConfig()`) hit the same exception. Code snippet as below (omitted the other producer config set in the config of type `HashMap<String,Object>`.

```java
			pulsarProducer = pulsarClient.newProducer()
							.topic(topicName)
							.producerName(producerName)
							.maxPendingMessages(2000)
							.loadConf(pulsarProducerProperties)
							.create();
```

I looked through the codes and couldn't find exactly what is the root cause of this error. Appreciate any pointers from the community.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by MarvinCai** [comment] 2022-09-06 15:34
I tried your code snippet, if you scroll down there're more exception message
`Caused by: com.fasterxml.jackson.databind.JsonMappingException: maxPendingMessagesAcrossPartitions needs to be >= maxPendingMessages`
which means you need to set none of them or set both of them.
And I'm afraid the doc is outdated, sorry for the confusion, seem default for `maxPendingMessages` and `maxPendingMessagesAcrossPartitions` are set to 0 in this pr: https://github.com/apache/pulsar/commit/11bfc0e95dc210c0dce70d1f53eb6eb43dbe835d, we will update the doc

**Comment by azmandzamiri** [comment] 2022-09-07 05:11
Thanks @MarvinCai. I just realised the exception cause message after inspecting it further. Yes, the docs is outdated and I suggest to also document the condition in the docs too - ie: maxPendingMessagesAcrossPartitions needs to be >= maxPendingMessages .

But another confusion I have is that the source code have marked `maxPendingMessagesAcrossPartitions` parameter as deprecated but doesn't suggest which property to use as an alternative. Any idea? And is it deprecated since 2.10.x ?

**Comment by MarvinCai** [comment] 2022-09-07 11:12
We should use memoryLimit instead: https://github.com/apache/pulsar/issues/13306

**Comment by tisonkun** [comment] 2022-12-10 15:00
Closed as answered.

**Closed by tisonkun** 2022-12-10 15:00 UTC
Labels: question
