### ISSUE TITLE
Pulsar SQL support for Protobuf

### ISSUE THREAD

**Issue by merlimat** [apache/pulsar#3554] opened 2019-02-08 20:52 UTC
Currently Pulsar SQL support querying topics where the schema is set on JSON or Avro format, but not on Protobuf.

Main reason is that regular Protobuf library doesn't support to deserialize binary proto data without having the Java (C++/Python) generated code for the POJOs. 

We should support this by having a protobuf binary parser that deserializes into a `GenericObject`. The information for mapping a protobuf field tag id into a field name is already present in the Pulsar schema. This was done explicitely for supporting this scenario.  Ref: https://github.com/apache/pulsar/blob/c40bb08f7e00b6e9dca2ca5f1a0a321113aab9a7/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/ProtobufSchema.java#L82-L98

**Comment by adeora** [comment] 2020-02-21 22:45
Is there any update on this feature? I'd love to have it for my own use cases.

**Comment by phemmer** [comment] 2020-04-19 00:35
Can we please get this limitation documented? Currently none of the [documentation](https://pulsar.apache.org/docs/en/sql-overview/) mentions the supported or unsupported schemas.

I had a suspicion that protobuf wasn't supported, as support for it in general is usually pretty scarce. But I couldn't make that determination until google turned up this issue.

**Comment by sijie** [comment] 2020-07-28 01:33
This is a duplicate of #7642. @hnail is picking up the task.

**Closed** 2021-03-12 23:46 UTC
Labels: component/sql, triage/week-31, type/feature
