### ISSUE TITLE
[Bug] Upload BYTES schema but got NULL schema type

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#18825] opened 2022-12-08 14:38 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Latest master

### Minimal reproduce step

root@stg-billing-broker-0:/pulsar# cat schema.txt
{
    "type": "BYTES",
    "schema": "",
    "properties": {}
}

root@stg-billing-broker-0:/pulsar# ./bin/pulsar-admin schemas upload persistent://public/default/asher-test -f schema.txt

root@stg-billing-broker-0:/pulsar# ./bin/pulsar-admin schemas get persistent://public/default/asher-test
{
  "version": 4,
  "schemaInfo": {
    "name": "asher-test",
    "schema": "",
    "type": "NONE",
    "properties": {}
  }
}

### What did you expect to see?

To keep consistent with the client side.
I think we should prevent the BYTES schema uploading
It's need to have discussion under the mailing list since it will change the existing behavior

### What did you see instead?

No

### Anything else?

No

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labuladong** [comment] 2022-12-09 02:36
Assign to me please

**Comment by labuladong** [comment] 2022-12-09 10:32
The root cause is `BYTES` is a negative enum:

https://github.com/apache/pulsar/blob/90f67587e31cc0cfb27773f85f18d607c9c5c324/pulsar-client-api/src/main/java/org/apache/pulsar/common/schema/SchemaType.java#L146-L155

Then `convertFromDomainType` convert `BYTES` to `NONE`

https://github.com/apache/pulsar/blob/90f67587e31cc0cfb27773f85f18d607c9c5c324/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java#L592-L598

**Comment by labuladong** [comment] 2022-12-09 10:33
I think there are two solutions:

1. Forbid users to upload the `BYTES` schema. This is the easiest way, don't need to change much code. (recommended)

I tried Java client `Producer<byte[]> producer = client.newProducer(Schema.BYTES)`, this producer won't auto-create a `BYTES` schema. If we allow users to upload a `BYTES` schema, that may cause inconsistency.

2. Add a `BYTES` type schema, that needs to add `BYTES` type to proto file:

https://github.com/apache/pulsar/blob/90f67587e31cc0cfb27773f85f18d607c9c5c324/pulsar-broker/src/main/proto/SchemaRegistryFormat.proto#L25-L48

And `client.newProducer(Schema.BYTES)` should also create `BYTES` type schema in schema factory.

**Comment by labuladong** [comment] 2022-12-10 01:53
mail list:
https://lists.apache.org/thread/672zmptfblwjmrf9z8336mk12r7csngf

**Closed** 2022-12-28 08:14 UTC
Labels: type/bug
