### ISSUE TITLE
Pulsar on k8s: broker start failure when set functionsWorkerEnabled=true

### ISSUE THREAD

**Issue by rocketraman** [apache/pulsar#5325] opened 2019-10-07 17:13 UTC
**Describe the bug**
The Kubernetes deployment sets `PF_pulsarFunctionsCluster` but this doesn't appear to get applied to `conf/functions_worker.yml`.

Looking at the source, it appears that the script `gen-yml-from-env.py` is supposed to update `functions_worker.yml`, but I think the script is missing the value `pulsarFunctionsCluster` in INT_KEYS  here: https://github.com/apache/pulsar/blob/60d2bfa389815b1769b36a0158059bfc3372a9a0/docker/pulsar/scripts/gen-yml-from-env.py#L30-L38

This is a followup to issue https://github.com/apache/pulsar/issues/2328.

**Comment by sijie** [comment] 2019-10-07 19:29
@rocketraman INT_KEYS are used for the settings whose value is Integer. So I don't think pulsarFunctionCluster is an INT key. 

You need to specify the function settings by prefixing the settings with "PF_". That says, you need to specify the system variable "PF_pulsarFunctionCluster", so that `gen-yml-from-env.py` can work as expected.

**Comment by cdbartholomew** [comment] 2019-10-07 19:33
@rocketraman expanding on @sijie's comment, I can confirm that if you set it as an environment variable, it gets applied. I have added this to my broker configmap for k8s:

```
apiVersion: v1
data:
  PF_pulsarFunctionsCluster: <clustername>
```
Then `gen-yml-from-env.py`  picks it up and applies it to `functions_worker.yml`.

**Comment by rocketraman** [comment] 2019-10-08 04:36
Hmm, for some reason it did not work for me. I have exactly that (based on the sample in the repo) and yet the broker was still starting up with an error looking for cluster "standalone".  Will try again tomorrow.

**Comment by stupidusername** [comment] 2019-10-21 21:02
I spent more than 12 hours on this...

There are 2 problems here:
- The functions worker needs to know the cluster name.
- The `public/functions` namespace needs to have that cluster set.

The list of `public/functions` clusters is set when the ZooKeeper service is created.

Here is my solution:

- `zookeeper.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
data:
...
  PF_pulsarFunctionsCluster: rings
  PF_numFunctionPackageReplicas: "2"
...
      containers:
        - name: zookeeper
          image: apachepulsar/pulsar:2.4.1
          command: ["sh", "-c"]
          args:
            - >
              bin/apply-config-from-env.py conf/zookeeper.conf &&
              bin/apply-config-from-env.py conf/pulsar_env.sh &&
              bin/generate-zookeeper-config.sh conf/zookeeper.conf &&
              bin/gen-yml-from-env.py conf/functions_worker.yml &&
              bin/pulsar zookeeper
...
```

- `broker.yaml`:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
data:
...
  functionsWorkerEnabled: "true"
  PF_pulsarFunctionsCluster: rings
  PF_numFunctionPackageReplicas: "2"
...
      containers:
        - name: broker
          image: apachepulsar/pulsar:2.4.1
          command: ["sh", "-c"]
          args:
            - >
              bin/apply-config-from-env.py conf/broker.conf &&
              bin/gen-yml-from-env.py conf/functions_worker.yml &&
              bin/apply-config-from-env.py conf/pulsar_env.sh &&
              bin/pulsar broker
...
```

I hope this helps you.

**Comment by rocketraman** [comment] 2019-10-21 21:24
@stupidusername  None of the zookeeper conf files have anything related to function worker cluster names in them (nor would I expect them to). I'm not certain why setting `PF_pulsarFunctionsCluster` for the zookeeper container would solve the issue. I don't even use the zookeeper that comes with Pulsar.

**Comment by stupidusername** [comment] 2019-10-21 21:47
I'm not adding that value to the ZooKeeper configuration. It is being added to `functions_worker.yml`. Both for the broker and ZooKeeper services.

After reading (https://github.com/apache/pulsar/issues/2328#issuecomment-411013973)[this] I got the idea that maybe there was an error during the creation of the ZooKeeper data.

I tried this workaround and it looks like it's working.

Keep in mind that`PF_` env variales are only applied if you add this line:

```
bin/gen-yml-from-env.py conf/functions_worker.yml &&
```

**Comment by rocketraman** [comment] 2019-10-22 01:58
I'd be very surprised if the container running ZooKeeper was responsible for reading `functions_worker.yml`, and initializing any data inside zookeeper from that file. If that is the case, I'd say that's a major bug. Nothing in the Pulsar docs indicates you need to initialize ZK this way, or indeed, even use the ZooKeeper provided by Pulsar.

**Comment by rocketraman** [comment] 2019-10-22 02:04
My ZK, which is a standalone ZK rather that the one started by `bin/pulsar zookeeper` does have this key `/admin/policies/public/functions`, and it does have the wrong value in it:

```
"replication_clusters":["standalone"]
```

so this means two things:

1) This value is being initialized from somewhere, but it isn't the `functions_worker.yaml` in the ZK container, because my ZK container does not have `functions_worker.yaml` in it.

2) It isn't one of the broker containers, because my broker container has this line in `functions_worker.yaml`:

```
# grep pulsarFunctionsCluster conf/functions_worker.yml 
pulsarFunctionsCluster: local
```

which is the correct value, and does not match what is in ZK.

**Comment by stupidusername** [comment] 2019-10-22 03:10
How did you initialize you cluster metadata?

**Comment by stupidusername** [comment] 2019-10-22 04:22
@rocketraman you were right. My solution does not make any sense. When I tried it for the first time I was working on a new cluster. Before that, I tried many other solutions but none of them work (including setting the `PF_` env variables in `broker.yaml`). And I think that's the issue here, once the clusters of `/admin/policies/public/functions` are set, they can't change.

Check this code from `pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Worker.java`:

```java
// getting namespace policy
log.info("Initializing Pulsar Functions namespace...");
try {
    try {
        admin.namespaces().getPolicies(workerConfig.getPulsarFunctionsNamespace());
    } catch (PulsarAdminException e) {
        if (e.getStatusCode() == Response.Status.NOT_FOUND.getStatusCode()) {
            // if not found than create
            try {
                Policies policies = new Policies();
                policies.retention_policies = new RetentionPolicies(-1, -1);
                policies.replication_clusters = new HashSet<>();
                policies.replication_clusters.add(workerConfig.getPulsarFunctionsCluster());
                admin.namespaces().createNamespace(workerConfig.getPulsarFunctionsNamespace(),
                        policies);
            } catch (PulsarAdminException e1) {
                // prevent race condition with other workers starting up
                if (e1.getStatusCode() != Response.Status.CONFLICT.getStatusCode()) {
                    log.error("Failed to create namespace {} for pulsar functions", workerConfig
                            .getPulsarFunctionsNamespace(), e1);
                    throw e1;
                }
            }
        } else {
            log.error("Failed to get retention policy for pulsar function namespace {}",
                    workerConfig.getPulsarFunctionsNamespace(), e);
            throw e;
        }
    }
    try {
        internalConf = admin.brokers().getInternalConfigurationData();
    } catch (PulsarAdminException e) {
        log.error("Failed to retrieve broker internal configuration", e);
        throw e;
    }
} finally {
    admin.close();
}
```

It looks like the values are only set if they are not found. What do you think?

**Comment by stupidusername** [comment] 2019-10-22 04:41
This may be the solution...

- If you are starting from fresh you need to make sure to configure `PF_pulsarFunctionsCluster` right before deploying the worker.

- If you already started the worker with a wrong configuration, you can try this out:

    ```bash
    $ bin/pulsar-admin namespaces set-clusters --cluster=<cluster> public/functions
    ```

    And then redeploy the worker with a fixed configuration.

**Comment by sijie** [comment] 2019-10-27 16:46
yeah I think @stupidusername already provided the right solution

**Comment by jiazhai** [comment] 2020-10-26 02:42
Would like to close this issue, since there was already a solution

**Closed by jiazhai** 2020-10-26 02:42 UTC
Labels: triage/week-43, type/bug
