### ISSUE TITLE
Update Pulsar to version 2.10.0,bin/pulsar-admin command invalid.

### ISSUE THREAD

**Issue by xiaobing0508** [apache/pulsar#15152] opened 2022-04-13 07:55 UTC
I build a Pulsar by using the master branch codebase.
When I use `pulsar-admin topics partitioned-stats` command,remind me 400 Bad Request.

**Comment by shibd** [comment] 2022-04-13 08:44
@xiaobing0508 Hi, Can you provide your complete command and exception information?

**Comment by xiaobing0508** [comment] 2022-04-13 08:45
/data/pulsar-2.10.0/bin/pulsar-admin topics partitioned-stats persistent://product/thor/data
HTTP 400 Bad Request

Reason: HTTP 400 Bad Request

**Comment by shibd** [comment] 2022-04-13 09:08
I didn't reproduce it, What do you return by executing the following command?
```
/data/pulsar-2.10.0/bin/pulsar-admin topics get-partitioned-topic-metadata persistent://product/thor/data
```

**Comment by xiaobing0508** [comment] 2022-04-13 09:10
{
  "partitions" : 4
}

**Comment by shibd** [comment] 2022-04-13 09:22
@xiaobing0508 Is your client version the same as the server version?

**Comment by xiaobing0508** [comment] 2022-04-13 09:26
It's the same. pulsar-admin command version is 2.10.0.

**Comment by lujiwen** [comment] 2022-05-18 12:42
I have the same problem with pulsar-2.10.0

**Comment by lujiwen** [comment] 2022-05-19 02:54
@xiaobing0508 Hi, have you resolved this problem? I have the same problem as you.

**Comment by xiaobing0508** [comment] 2022-05-19 02:57
No,waiting new version..

**Comment by lujiwen** [comment] 2022-05-19 06:23
@xiaobing0508 The weird thing is that, my problem get resolved, but I did nothing, after tens of hours. But I have another problem, I was trying to get a partitioned topic internal stats by pulsar admin, and the response is 500 internal error, with exception on the broker "Error while recovering ledger"

**Comment by xiaobing0508** [comment] 2022-05-19 06:26
This problem is only for viewing topic stats .

**Comment by lujiwen** [comment] 2022-06-02 01:28
@xiaobing0508 yes, and I find the bad request exception is only thrown for the topic who has a huge throughput.

**Comment by lujiwen** [comment] 2022-06-02 03:51
I looked into the source code, and I found this may highly be related to this configuration 'httpMaxRequestSize',  I guess getting partitioned topic stats can possibly increase HTTP request body size @shibd

**Comment by xiaobing0508** [comment] 2022-06-02 03:54
Have you found a solution?

**Comment by jabbaugh** [comment] 2022-06-02 21:47
We are seeing the same issue. 
The steps to produce for us:
- Actively publish to the partitioned topic
- Run `bin/pulsar-admin` topics partitioned-stats {TOPIC}`

**Comment by fistan684** [comment] 2022-06-02 22:06
We recently upgraded to 2.10 as well and have hit this issue. When we turn off the producers we can correctly get partitioned stats but with any level of input the command fails. We are running these commands from the brokers (via CLI) and from the java client. We have business logic, alerts, and scaling around the backlog amount so this is definitely causing some issues for us. We're also using the matching client version.

broker-deployment-8454bf5ddd-phcxl:/pulsar$ bin/pulsar-admin topics partitioned-stats persistent://prod/input/{TOPIC}
HTTP 400 Bad Request

Reason: HTTP 400 Bad Request

@shibd

**Comment by jabbaugh** [comment] 2022-06-03 01:59
Hitting the broker with curl (/admin/v2/persistent/{TENANT}/{NAMESPACE}/{TOPIC}/partitioned-stats?perPartition=false&getPreciseBacklog=false&subscriptionBacklogSize=false) does give us:
`(was java.lang.NullPointerException) (through reference chain: org.apache.pulsar.common.policies.data.stats.PartitionedTopicStatsImpl["publishers"])`

**Comment by michaeljmarshall** [comment] 2022-06-03 02:39
@jabbaugh - that's a very helpful error message. I see that PIP 79 modified the partitioned topic stats: https://github.com/apache/pulsar/wiki/PIP-79%3A-Reduce-redundant-producers-from-partitioned-producer#change-partitionedtopicstats-about-producer. That PIP only just took affect in 2.10. I'm taking a closer look at that now.

**Comment by michaeljmarshall** [comment] 2022-06-03 05:03
Quick update: I reproduced this behavior using a small standalone cluster on my machine. 

1. Run `bin/pulsar standalone`.
2. Run `bin/pulsar-admin topics create-partitioned-topic -p 1 test` (you only need a single partition).
3. Start two producers that will maintain an active connection `bin/pulsar-perf produce -r 1 test`. (I didn't see any errors when connecting a single producer.)
4. Run `bin/pulsar-admin topics partitioned-stats test` and get:

```
HTTP 400 Bad Request

Reason: HTTP 400 Bad Request
```

Observations: it is relevant that this is reproducible with a single partition. It is also relevant that two producers need to be connected. When I ran the `bin/pulsar-admin topics partitioned-stats test` command with a single producer connected, I got the following
```
$ bin/pulsar-admin topics partitioned-stats test
{
  "msgRateIn" : 0.0,
  "msgThroughputIn" : 0.0,
  "msgRateOut" : 0.0,
  "msgThroughputOut" : 0.0,
  "bytesInCounter" : 5380,
  "msgInCounter" : 5,
  "bytesOutCounter" : 0,
  "msgOutCounter" : 0,
  "averageMsgSize" : 0.0,
  "msgChunkPublished" : false,
  "storageSize" : 25824,
  "backlogSize" : 0,
  "publishRateLimitedTimes" : 0,
  "earliestMsgPublishTimeInBacklogs" : 0,
  "offloadedStorageSize" : 0,
  "lastOffloadLedgerId" : 0,
  "lastOffloadSuccessTimeStamp" : 0,
  "lastOffloadFailureTimeStamp" : 0,
  "publishers" : [ {
    "msgRateIn" : 0.0,
    "msgThroughputIn" : 0.0,
    "averageMsgSize" : 0.0,
    "chunkedMessageRate" : 0.0,
    "producerId" : 0,
    "supportsPartialProducer" : false
  } ],
  "waitingPublishers" : 0,
  "subscriptions" : { },
  "replication" : { },
  "nonContiguousDeletedMessagesRanges" : 0,
  "nonContiguousDeletedMessagesRangesSerializedSize" : 0,
  "compaction" : {
    "lastCompactionRemovedEventCount" : 0,
    "lastCompactionSucceedTimestamp" : 0,
    "lastCompactionFailedTimestamp" : 0,
    "lastCompactionDurationTimeInMills" : 0
  },
  "metadata" : {
    "partitions" : 1
  },
  "partitions" : { }
}
```

As @jabbaugh's error indicates, this must have something to do with the way that the publishers object is being generated.

**Comment by michaeljmarshall** [comment] 2022-06-03 05:37
Looks like this is fixed by https://github.com/apache/pulsar/pull/15502, which is already cherry picked to `branch-2.10`, so it will be released in version 2.10.1. I am going to close this since it has a resolution.

Here is some additional research I was about to comment before finding the above PR:

The root cause is how the `TopicStatsImpl#getPublishers` method is implemented. I modified test `AdminApi2Test#testBacklogNoDelayedForPartitionedTopic` so that it'd create two producers and then added some extra logging and got this null pointer:

```
java.lang.NullPointerException: null
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469) ~[?:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:220) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1515) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[?:?]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.apache.pulsar.common.policies.data.stats.TopicStatsImpl.getPublishers(TopicStatsImpl.java:138) ~[pulsar-common-2.10.0.jar:2.10.0]
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalGetPartitionedStats$86(PersistentTopicsBase.java:1349) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.apache.pulsar.client.admin.internal.TopicsImpl$11.completed(TopicsImpl.java:633) ~[pulsar-client-admin-original-2.10.0.jar:2.10.0]
	at org.apache.pulsar.client.admin.internal.TopicsImpl$11.completed(TopicsImpl.java:630) ~[pulsar-client-admin-original-2.10.0.jar:2.10.0]
	at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:861) ~[jersey-client-2.34.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229) ~[jersey-client-2.34.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62) ~[jersey-client-2.34.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173) ~[jersey-client-2.34.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.34.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.34.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.34.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.34.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.34.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288) ~[jersey-common-2.34.jar:?]
	at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:173) ~[jersey-client-2.34.jar:?]
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$apply$1(AsyncHttpConnector.java:228) ~[pulsar-client-admin-original-2.10.0.jar:2.10.0]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$4(AsyncHttpConnector.java:270) ~[pulsar-client-admin-original-2.10.0.jar:2.10.0]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) [?:?]
	at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222) [async-http-client-2.12.1.jar:?]
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257) [async-http-client-2.12.1.jar:?]
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241) [async-http-client-2.12.1.jar:?]
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:114) [async-http-client-2.12.1.jar:?]
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:143) [async-http-client-2.12.1.jar:?]
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78) [async-http-client-2.12.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.74.Final.jar:4.1.74.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

It looks like the underlying issue results in a 400 because that is how Jackson handles the exception.

**Closed by michaeljmarshall** 2022-06-03 05:37 UTC
Labels: type/bug

**Comment by fistan684** [comment] 2022-06-03 15:25
Thank you @michaeljmarshall  - appreciate the thorough review. :)

**Comment by lujiwen** [comment] 2022-06-07 02:54
Thank you @michaeljmarshall
