### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [apache/pulsar#4663] opened 2019-07-02 17:28 UTC
Hi
The following lines have cryptographic API misuses. <br> File name => pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java: Line number => 147: API name => MessageDigest:Unexpected call to method <java.security.MessageDigest: byte[] digest()> on object of type java.security.MessageDigest. Expect a call to one of the following methods <java.security.MessageDigest: void update(byte[])>,<java.security.MessageDigest: void update(byte[],int,int)>,<java.security.MessageDigest: byte[] digest(byte[])>,<java.security.MessageDigest: void update(java.nio.ByteBuffer)>,<java.security.MessageDigest: void update(byte)><BR> File name => pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java: Line number => 157: API name => MessageDigest:<BR>

**Comment by merlimat** [comment] 2019-07-02 17:49
I cannot follow exactly what is the problem here. Can you share a code example that would show the problem?

**Comment by sijie** [comment] 2019-07-09 10:12
This seems to be a duplicate of #4662

**Closed by sijie** 2019-07-09 10:12 UTC
