### ISSUE TITLE
[Doc] Broken links at /admin-api-clusters

### ISSUE THREAD

**Issue by visortelle** [apache/pulsar#19604] opened 2023-02-22 17:51 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

https://pulsar.apache.org/docs/2.11.x/admin-api-clusters/#update-peer-cluster-data

- [ ] Pulsar admin doc
- [ ] pulsar-admin
<img width="847" alt="Screenshot 2023-02-22 at 5 13 20 PM" src="https://user-images.githubusercontent.com/9302460/220686791-a30ee883-05c4-40aa-97ca-ef26839cab4d.png">

- [ ] create
<img width="825" alt="Screenshot 2023-02-22 at 5 11 46 PM" src="https://user-images.githubusercontent.com/9302460/220686295-504b1043-0c7b-47df-9358-630a00f01c3e.png">

- [ ] There are more broken links to fix on this page. Please check.

### What is your suggestion?

Fix it.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by momo-jun** [comment] 2023-02-27 06:16
I've checked this page and the links you mentioned, all of which redirects to the following page. @visortelle  Is this the issue you meant? 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/60642177/221457112-e77db82a-c05d-4020-a818-bb31092bf3f6.png">

Actually, it's by design, and users can select a specific version to continue. Feel free to share your ideas.

**Comment by visortelle** [comment] 2023-02-27 09:19
@momo-jun There are links on the page that definitely don't work. For example:

<img width="512" alt="Screenshot 2023-02-27 at 9 36 32 AM" src="https://user-images.githubusercontent.com/9302460/221513953-0c14ef8c-a609-47bf-84aa-c67e83fbbae3.png">

Both REST API links:
<img width="980" alt="Screenshot 2023-02-27 at 9 36 53 AM" src="https://user-images.githubusercontent.com/9302460/221514013-1b2fec4d-6206-4291-afd2-f06fde7ed957.png">

5 minutes ago @RobertIndie  already created a separate issue for it: https://github.com/apache/pulsar/issues/19644

---

Regarding that many links about CLI commands refer to the same page.

<img width="545" alt="Screenshot 2023-02-27 at 9 42 46 AM" src="https://user-images.githubusercontent.com/9302460/221515264-3389ec11-8094-4881-897c-2a86a414d27e.png">

As I see, it's possible to specify a link to specific command for a particular Pulsar version.
https://pulsar.apache.org/tools/pulsar-admin/2.11.0-SNAPSHOT/#-em-create-em-

<img width="924" alt="Screenshot 2023-02-27 at 9 48 30 AM" src="https://user-images.githubusercontent.com/9302460/221516498-35aad5e2-1e9c-4007-8cb6-14da96a851c0.png">

If I understand it right, the problem is how to take the current version from the Docusaurus context (2.11.x), and convert it to the version that is used in auto-generated CLI tools documentation (2.11.0-SNAPSHOT). Then use it as a template variable in the docs markdown.

There is some discussion on this topic here: https://github.com/facebook/docusaurus/issues/395. But I'm not ready to dig into this now.

As a docs reader, I the problem inconvenient, but not critical to run fix it right now. :)

Maybe @tisonkun has any ideas?

**Comment by tisonkun** [comment] 2023-02-27 10:47
@visortelle I don't go through the whole issue, but for `tools`, I believe it should be superseded by https://pulsar.apache.org/reference/. In the site code if you search `version` in `*.js` and `*.ts` you may find some functions to handling versions from the page context.

**Comment by momo-jun** [comment] 2023-02-27 14:01
@visortelle Thanks for the clarification. Now I understand the scope of this issue is all about the links to REST APIs. Ping @urfreespace to take a look at this issue.

> If I understand it right, the problem is how to take the current version from the Docusaurus context (2.11.x), and convert it to the version that is used in auto-generated CLI tools documentation (2.11.0-SNAPSHOT). Then use it as a template variable in the docs markdown.

Agree. This behavior is more user-friendly. This challenge of implementing it still exists if we use https://pulsar.apache.org/reference/ as the reference link.

**Comment by momo-jun** [comment] 2023-03-01 03:31
REST API links should have been fixed by @urfreespace through https://github.com/apache/pulsar-site/pull/439. I will double-check the result later today and close this issue.

For switching links from https://pulsar.apache.org/tools/ to https://pulsar.apache.org/reference/, ping @Anonymitaet to take a look. I'm not sure whether the `tools` site can be abandoned.

**Comment by Anonymitaet** [comment] 2023-03-01 05:58
+1 on replacing https://pulsar.apache.org/tools/ with https://pulsar.apache.org/reference/

**Comment by momo-jun** [comment] 2023-03-01 12:11
@visortelle I've filed https://github.com/apache/pulsar/issues/19676 to track the issue of using the reference site (replacing tools) with versioned links, and closed this one. Thank you.

**Closed by momo-jun** 2023-03-01 12:11 UTC
Labels: doc-required
