### ISSUE TITLE
[Bug] python client version is inconsistent in document and pypi

### ISSUE THREAD

**Issue by labuladong** [apache/pulsar#19231] opened 2023-01-14 06:13 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.11.0

### Minimal reproduce step

I follow [the document](https://pulsar.apache.org/docs/2.11.x/client-libraries-python/) to install 2.11.0 python client:
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/37220920/212458525-02bdde9f-7fa0-42ce-9ddd-aadcf472fec9.png">

### What did you expect to see?

Install successfully.

### What did you see instead?

```shell
$ pip install 'pulsar-client==2.11.0'
ERROR: Could not find a version that satisfies the requirement pulsar-client==2.11.0 (from versions: 2.8.0, 2.8.1, 2.9.1, 2.9.2, 2.10.0, 2.10.1, 3.0.0)
ERROR: No matching distribution found for pulsar-client==2.11.0
```

### Anything else?

In [Pypi](https://pypi.org/project/pulsar-client/#history) the latest version is 3.0:

![image](https://user-images.githubusercontent.com/37220920/212458629-d0ec9209-c757-4baa-856e-7def042468a0.png)

I think there is something wrong in release process or the document.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment] 2023-01-14 06:37
Close as a duplicate of https://github.com/apache/pulsar/issues/19121.

I don't have time to prepare a patch yet, but can be in this month. @labuladong you're welcome to leave comment on #19121 or send a patch against https://github.com/apache/pulsar-site.

**Closed** 2023-01-14 06:37 UTC
Labels: type/bug
