### ISSUE TITLE
Support get topic applied policy

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#9216] opened 2021-01-15 08:23 UTC
**Is your feature request related to a problem? Please describe.**
Provide a way to get the applied policy of the topic. In Pulsar, the topic will apply the topic level policy if present or apply the namespace policy if present or use the broker level configuration. It needs to support get the applied policy for a topic that might use the namespace policy or topic policy or broker level default configuration. 

**Describe the solution you'd like**
Add "--applied" for the get policy cmd. For example:

```
bin/pulsar-admin topics get-retention --applied
```

- [x]   1. MessageTTL
- [x]   2. Retention Policy
- [x]   3. Message Dispatch Rate
- [x]   4. Backlog Quota
- [x]   5. Persistence Policy
- [x]   6. Max Producer
- [x]   7. Max Consumer
- [x]   8. Compaction Threshold
- [x]   9. Deduplication
- [x]   10. Offload Policy
- [x]   11. MaxUnackMessagesPerConsumer
- [x]   12. MaxUnackMessagesPerSubscription
- [x]   13. DelayedDeliveryPolicies
- [x]   14. Inactive topic policy

**Comment by 315157973** [comment] 2021-01-17 02:50
I will work on it

**Comment by Anonymitaet** [comment] 2021-01-22 02:57
@315157973 thanks for your contribution.

Could you please add doc once you finish all code work? 
[Pulsar admin doc](http://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/#-em-get-retention-em--51) and [REST API doc](https://pulsar.apache.org/admin-rest-api/?version=master&apiversion=v2#tag/persistent-topic) are automatically generated from codes, you can add corresponding descriptions in the code files. Thanks again.

**Comment by 315157973** [comment] 2021-01-22 03:31
> @315157973 thanks for your contribution.
> 
> Could you please add doc once you finish all code work?
> [Pulsar admin doc](http://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/#-em-get-retention-em--51) and [REST API doc](https://pulsar.apache.org/admin-rest-api/?version=master&apiversion=v2#tag/persistent-topic) are automatically generated from codes, you can add corresponding descriptions in the code files. Thanks again.

OK

**Comment by Anonymitaet** [comment] 2021-02-25 03:00
@315157973 @codelipenghui will these code changes apply to 2.7.1?

**Comment by codelipenghui** [comment] 2021-03-02 04:12
@Anonymitaet No, this will available in 2.8.0

**Comment by lhotari** [comment] 2021-03-07 16:43
@codelipenghui @315157973 I'd suggest fixing #9711 before making more changes to policy handling. WDYT?

**Comment by 315157973** [comment] 2021-03-07 17:20
> @codelipenghui @315157973 I'd suggest fixing #9711 before making more changes to policy handling. WDYT? 


I will fix thread safety issues in a unified way，will not affect this issue

**Comment by lhotari** [comment] 2021-03-07 17:33
> I will fix thread safety issues in a unified way

@315157973 that would be very good. How?

**Comment by codelipenghui** [comment] 2021-03-08 00:20
@lhotari This task is to support get applied policy for a topic, I don't understand why the new feature needs to wait for #9711. The topic policy does not persistent to zookeeper.

**Comment by lhotari** [comment] 2021-03-08 06:21
> This task is to support get applied policy for a topic, I don't understand why the new feature needs to wait for #9711. The topic policy does not persistent to zookeeper.

I have added a comment here: https://github.com/apache/pulsar/pull/9832/files#r589192556

The thread safety issue isn't related to Zookeeper. It's mainly about unsafe mutation and access of HashMaps.

**Comment by codelipenghui** [comment] 2021-03-08 07:15
@lhotari Thanks for the clarification. I don't think it should block the new feature implement. I understand your concern, if we merge more PRs related to the policies, we need to do more changes when fixing #9711. But for community cooperation, we should not block the new features. #9216 is planned to release in 2.8.0. So we can confirm before release 2.8.0, #9711 can be fixed, is this works for you?

**Comment by lhotari** [comment] 2021-03-08 07:28
> @lhotari Thanks for the clarification. I don't think it should block the new feature implement. I understand your concern, if we merge more PRs related to the policies, we need to do more changes when fixing #9711. But for community cooperation, we should not block the new features. #9216 is planned to release in 2.8.0. So we can confirm before release 2.8.0, #9711 can be fixed, is this works for you?

@codelipenghui Makes sense. 

Fixing #9711 might have broader impacts and dealing with it asap would be important. I hope it gets prioritized since it seems that the issue is cross-cutting and the current unsafe pattern is copied over to new feature development like we have seen in this case. 
There might be simple fixes to address some of the issues, for example replacing plain HashMaps with thread safe wrappers (Collections.synchronizedMap) or ConcurrentHashMaps, but that could leave some data consistency issues.

**Comment by Anonymitaet** [comment] 2021-04-09 08:05
@315157973 thanks for your great contribution! 

Since you've finished all code work, could u pls add docs for them? Then users know your changes and how to use it.

I think the descriptions should be added to [pulsar-admin](http://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/), [REST API](https://pulsar.apache.org/admin-rest-api/?version=master&apiversion=v2), or [Java admin API](https://pulsar.apache.org/api/admin/) if needed.

Below is an example.
![image](https://user-images.githubusercontent.com/50226895/114149312-586cf800-994d-11eb-97af-e98b2df1a864.png)

Feel free to ping me if you need doc review.

**Comment by 315157973** [comment] 2021-04-09 09:40
There are descriptions in my code, and we already have automatic document generation tools, so I don’t need to add them manually, right? @Anonymitaet

**Comment by 315157973** [comment] 2021-04-09 09:41
![image](https://user-images.githubusercontent.com/9758905/114161556-ccfa6380-995a-11eb-95b9-9c4793e1f677.png)

Looks like it has been generated

**Comment by Anonymitaet** [comment] 2021-04-09 09:52
@315157973 yes, the "docs" are added in the code files and they will be shown on websites automatically. 

One thing should pay attention to is that if your changes apply to [pulsar-admin](http://pulsar.apache.org/tools/pulsar-admin/2.8.0-SNAPSHOT/), [REST API](https://pulsar.apache.org/admin-rest-api/?version=master&apiversion=v2), and [Java admin API](https://pulsar.apache.org/api/admin/), make sure the "docs" are added there. Do your changes apply to these 3 websites?

**Comment by 315157973** [comment] 2021-04-09 10:10
"docs" are added in `pulsar-admin`, `REST API`. 
The `Java admin API` does not seem to be automatically generated yet? 
Many new APIs do not exist, not just those I added

**Comment by Anonymitaet** [comment] 2021-04-09 12:51
@315157973 If you want to add docs for [Java admin API](https://pulsar.apache.org/api/admin/), you may need to add descriptions to [these files](https://github.com/apache/pulsar/tree/master/pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin).

**Comment by 315157973** [comment] 2021-04-10 04:33
All of my new APIs have descriptions. However,  my new APIs and many old APIs with descriptions are not displayed in `Java admin API`. Please help to check the tool. @Anonymitaet 
For example:
https://github.com/apache/pulsar/blob/56bad04d702311cffed2ba94ff35f170af185eda/pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java#L1660-L1674

This API has been around for a long time, but it does not appear in the `Java admin API`

**Comment by Anonymitaet** [comment] 2021-04-12 09:33
@315157973 

`setMessageTTL(String topic, int messageTTLInSecond)` is shown on https://pulsar.apache.org/api/admin/2.7.0-SNAPSHOT/ but not shown on https://pulsar.apache.org/api/admin/.

I've checked all commands and documented details [here](https://docs.google.com/spreadsheets/d/1GYi9O4bwL-7spFiBcXJ82wB4QSwlCDkSubDUDSBDLjI/edit#gid=0). I found that all commands (except `setMessageTTL(String topic, int messageTTLInSecond`) are not shown on any version of the Java Admin API website.

**Comment by Anonymitaet** [comment] 2021-04-12 09:38
Hi @tuteng 

@315157973 has added various commands and docs correspondingly in their source code files. 

Docs for pulsar-admin and REST API are shown on websites but **docs for Java Admin API are not shown** on any version of the Java Admin API website (https://pulsar.apache.org/api/admin/2.7.0-SNAPSHOT/ or https://pulsar.apache.org/api/admin/).

**Do you have any clues?** Many thanks.

**Comment by Anonymitaet** [comment] 2021-04-13 09:03
Hi @tuteng could u pls give us some instructions? Many thanks.

**Comment by Anonymitaet** [comment] 2021-04-15 04:26
@315157973 the docs you added for Java Admin API should be shown on https://pulsar.apache.org/api/admin/2.8.0-SNAPSHOT/, however, currently https://pulsar.apache.org/api/admin/2.8.0-SNAPSHOT/ is not generated yet and it should be generated after 2.7.1 is released. I've discussed w/ @tuteng and opened [this issue](https://github.com/apache/pulsar/issues/10237) to track. He will handle it.

Since code work has been finished and all docs have been added to source code files (pulsar-admin, REST API, and Java admin API), I'll close this issue and keep an eye for the [commands that should be shown on https://pulsar.apache.org/api/admin/2.8.0-SNAPSHOT/](https://docs.google.com/spreadsheets/d/1GYi9O4bwL-7spFiBcXJ82wB4QSwlCDkSubDUDSBDLjI/edit#gid=0) once https://pulsar.apache.org/api/admin/2.8.0-SNAPSHOT/ is generated.

**Closed by Anonymitaet** 2021-04-15 04:26 UTC
Labels: doc-required, triage/week-3, type/feature
