### ISSUE TITLE
Pulsar SQL is not able to read the latest message

### ISSUE THREAD

**Issue by sijie** [apache/pulsar#3828] opened 2019-03-15 03:40 UTC
**Describe the bug**

Pulsar SQL is always lacking one message when querying pulsar topics.

**Expected behavior**

"read-my-write" semantic.

if I write a bunch of messages to pulsar topics, and issue a query after "my-write", I should be able to query all the messages I written.

**Reason**

The problem is due to broker doesn't advance LAC, so when pulsar sql bypasses broker to query the data, it can only read entries up to the LAC that all the bookies learned. 

**Fixes**

Enable periodically write lac on broker.

**Comment by jerrypeng** [comment] 2019-03-15 06:29
@sijie yup have discussed this issue before with @merlimat but we decided not to take any action at that time because we reasoned that Pulsar is a streaming system thus we expect users to continuously pump data into pulsar and not just one time batch thus this wouldn't be an issue since LAC will eventually get updated if there is continuous data

**Comment by sijie** [comment] 2019-03-15 06:45
@jerrypeng this is not just about not being able to read the event, but also about the latency (how fast it can query the data). current assumption is assuming there are are events "eventually" arrive and advance the LAC, which will significantly delay the messages being visible to users if the events are delayed. so I think we still need to enable explicit write lac on broker, so the lac will be advanced within a SLA. 

The feature is already in bookkeeper. It is just a matter to enable it and make sure it is working as expected. If pulsar broker doesn't want this feature to be turned on by default, we can make it configurable and turned off by default. If people want this feature, they can turn it on. I don't think we should just ignore this fact and try to explain to people who don't really understand how the underlying stuff works.

**Comment by jerrypeng** [comment] 2019-03-15 07:00
@sijie I totally agree we should add something like this.  I was just presenting some previous thoughts we have had on this problem.

**Comment by merlimat** [comment] 2019-03-19 17:41
Yes, we should have a way to configure the explicit LAC update on the topics and have some reasonable default.

Though, should this be for 2.3.1? I think it would more be appropriate for 2.4 since it's not a bug.. but rather a current limitation.

**Comment by sijie** [comment] 2019-03-27 06:08
@merlimat we can move this to 2.4.0

**Comment by atris** [comment] 2020-01-23 13:58
Hi, If nobody is working on this, can I please be assigned this?

**Comment by sijie** [comment] 2020-01-24 03:56
@atris the bookkeeper change has made to Pulsar. #5822 is enabling the explicit lac configuration. once that is fixed, this task is done.

**Comment by codelipenghui** [comment] 2020-02-10 00:34
close via #5822

**Closed by codelipenghui** 2020-02-10 00:34 UTC
Labels: component/sql, triage/week-44, type/bug

**Comment by codelipenghui** [comment] 2020-05-19 05:14
This issue is fixed by #6908 and #6908 is released in 2.5.2, So I add `release/2.5.2` tag for this issue.
