### ISSUE TITLE
Several Chinese documents are not formatted correctly

### ISSUE THREAD

**Issue by fantapsody** [apache/pulsar#8603] opened 2020-11-18 02:34 UTC
**Describe the bug**
I found several Chinese documents are not formatted correctly:
https://pulsar.apache.org/docs/zh-CN/reference-configuration/
https://pulsar.apache.org/docs/zh-CN/next/reference-configuration/

**To Reproduce**
Just open the URLs above.

**Expected behavior**
The Chinese document should have the same format as the English document.

**Screenshots**
![image](https://user-images.githubusercontent.com/2741703/99475310-416f3e80-2989-11eb-8b83-3c649cc217c0.png)
![image](https://user-images.githubusercontent.com/2741703/99475336-4df39700-2989-11eb-8c5e-5712bd41cf37.png)

**Desktop (please complete the following information):**
 - Browser: Microsoft Edge

**Comment by Jennifer88huang** [comment] 2020-11-18 08:59
@fantapsody Thanks for raising the issue. Someone might have deleted some metadata when translating. 
@sijia-w could you please help check the metadata in the Crowdin and fix it? Any block, please let me know. Thank you.

**Comment by Anonymitaet** [comment] 2022-02-28 04:11
The format of the corresponding [English page](https://pulsar.apache.org/docs/en/next/reference-configuration/) is correct.  @tuhaihe you may want to fix this

**Comment by tuhaihe** [comment] 2022-03-04 07:46
@Anonymitaet I think these problems are caused by the translation system, not because of the translation text. I can do some Chinese translation for the new website to see if still have these problems.

**Comment by tisonkun** [comment] 2022-12-06 09:43
Closed as translations are archived #17810.

**Closed by tisonkun** 2022-12-06 09:43 UTC
Labels: type/bug, doc-required
