### ISSUE TITLE
Deduplication causes a lot of Full GCs

### ISSUE THREAD

**Issue by nkurihar** [apache/pulsar#3535] opened 2019-02-07 00:43 UTC
**Describe the bug**

**2019/02/14 Added**

In our experiments, we found that enabling deduplication causes a lot of Full GCs in Brokers, which 
 seems to cause session expiration from ZooKeepers and finally shutdown.

**2019/02/07 Original report of unexpected Broker shutdown**

We have seen unexpected Broker shutdown.

1. There were LedgerFencedExceptions for a lot of ledgers:
```
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] WARN  o.a.bookkeeper.client.PendingAddOp   - Fencing exception on write: L9104171 E28233 on xxx.xx.xx.xx:3181
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] ERROR o.a.bookkeeper.client.LedgerHandle   - Closing ledger 9104171 due to LedgerFencedException: Ledger has been fenced off. Some other client must have opened it to read
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] WARN  o.a.bookkeeper.client.PendingAddOp   - Fencing exception on write: L9104171 E28234 on xxx.xx.xx.xx:3181
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] ERROR o.a.bookkeeper.client.LedgerHandle   - Closing ledger 9104171 due to LedgerFencedException: Ledger has been fenced off. Some other client must have opened it to read
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] WARN  o.a.bookkeeper.client.PendingAddOp   - Fencing exception on write: L9104171 E28235 on xxx.xx.xx.xx:3181
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] ERROR o.a.bookkeeper.client.LedgerHandle   - Closing ledger 9104171 due to LedgerFencedException: Ledger has been fenced off. Some other client must have opened it to read
...
```

2. There were a lot of "Failed to create producer: Producer with name geo-replicator".
```
01:47:09.907 [pulsar-io-21-31] ERROR o.a.pulsar.client.impl.ProducerImpl  - [persistent://<topicname>] [pulsar.repl.<localcluster>] Failed to create producer: Producer with name 'pulsar.repl.<localcluster>' is already connected to topic
```

3. Finally, Broker suddenly stopped with
```
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] ERROR o.a.p.z.ZooKeeperSessionWatcher      - ZooKeeper session already expired, invoking shutdown
```

**Additional context**
Broker OS: CentOS Linux release 7.6.1810
Broker version: 2.1.1

**Comment by sijie** [comment] 2019-02-07 02:30
@nkurihar *fencing* means there are other brokers taking over the ownership of topics. those brokers which took over the ownership has opened the topics and fenced the old ledgers. 

by looking into the description here, it seems to be *reasonable* to me. I think it is somehow related to zookeeper session expired. when zookeeper session expired happened, the load manager has discovered the broker disappeared from zookeeper and topic bundles are re-assigned to other brokers, those brokers fenced the topics, hence the original broker will see LedgerFencedException and Producer will fail to create. 

I think the exception should be self-recovered. did it self-recover? @nkurihar

**Comment by nkurihar** [comment] 2019-02-07 04:22
@sijie Thanks for your help!

> I think the exception should be self-recovered. did it self-recover?

No.
After ZK session expired, Broker becoame down.
```
01:47:09.961 [pulsar-ordered-OrderedExecutor-4-0-SendThread(zk101.pulsar.xxx.xx:2181)] WARN  org.apache.zookeeper.ClientCnxn      - Unable to reconnect to ZooKeeper service, session 0x3048c994034e22a has expired
01:47:09.961 [pulsar-ordered-OrderedExecutor-4-0-SendThread(zk101.pulsar.xxx.xx:2181)] INFO  org.apache.zookeeper.ClientCnxn      - Unable to reconnect to ZooKeeper service, session 0x3048c994034e22a has expired, closing socket connection
01:47:09.961 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  o.a.p.zookeeper.ZooKeeperDataCache   - [State:CLOSED sessionid:0x3048c994034e22a local:/xx.xx.xx.xx:37204 remoteserver:zk101.pulsar.xxx.xx/xx.xx.xx.xx:2181 lastZxid:171918958881 xid:7602221 sent:7602223 recv:8325363 queuedpkts:73 pendingresp:0 queuedevents:1] Received ZooKeeper watch event: WatchedEvent state:Expired type:None path:null
01:47:09.961 [pulsar-ordered-OrderedExecutor-4-0-EventThread] WARN  o.a.p.zookeeper.LocalZooKeeperCache  - Lost connection from local ZK. Invalidating the whole cache.
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  o.a.p.z.ZooKeeperChildrenCache       - [State:CLOSED sessionid:0x3048c994034e22a local:xx.xx.xx.xx/xx.xx.xx.xx:37204 remoteserver:zk101.pulsar.xxx.xx/xx.xx.xx.xx:2181 lastZxid:171918958881 xid:7602221 sent:7602223 recv:8325363 queuedpkts:73 pendingresp:0 queuedevents:1] Received ZooKeeper watch event: WatchedEvent state:Expired type:None path:null
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] WARN  o.a.p.zookeeper.LocalZooKeeperCache  - Lost connection from local ZK. Invalidating the whole cache.
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  o.a.p.z.ZooKeeperChildrenCache       - [State:CLOSED sessionid:0x3048c994034e22a local:xx.xx.xx.xx/xx.xx.xx.xx:37204 remoteserver:zk101.pulsar.xxx.xx/xx.xx.xx.xx:2181 lastZxid:171918958881 xid:7602221 sent:7602223 recv:8325363 queuedpkts:73 pendingresp:0 queuedevents:1] Received ZooKeeper watch event: WatchedEvent state:Expired type:None path:null
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] WARN  o.a.p.zookeeper.LocalZooKeeperCache  - Lost connection from local ZK. Invalidating the whole cache.
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  o.a.p.zookeeper.ZooKeeperDataCache   - [State:CLOSED sessionid:0x3048c994034e22a local:xx.xx.xx.xx/xx.xx.xx.xx:37204 remoteserver:zk101.pulsar.xxx.xx/xx.xx.xx.xx:2181 lastZxid:171918958881 xid:7602221 sent:7602223 recv:8325363 queuedpkts:73 pendingresp:0 queuedevents:1] Received ZooKeeper watch event: WatchedEvent state:Expired type:None path:null
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] WARN  o.a.p.zookeeper.LocalZooKeeperCache  - Lost connection from local ZK. Invalidating the whole cache.
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  o.a.p.zookeeper.ZooKeeperDataCache   - [State:CLOSED sessionid:0x3048c994034e22a local:xx.xx.xx.xx/xx.xx.xx.xx:37204 remoteserver:zk101.pulsar.xxx.xx/xx.xx.xx.xx:2181 lastZxid:171918958881 xid:7602221 sent:7602223 recv:8325363 queuedpkts:73 pendingresp:0 queuedevents:1] Received ZooKeeper watch event: WatchedEvent state:Expired type:None path:null
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] WARN  o.a.p.zookeeper.LocalZooKeeperCache  - Lost connection from local ZK. Invalidating the whole cache.
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] ERROR o.a.b.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  o.a.b.zookeeper.ZooKeeperClient      - ZooKeeper session 3048c994034e22a is expired from zk100.pulsar.xxx.xx,zk101.pulsar.xxx.xx,zk102.pulsar.xxx.xx,zk103.pulsar.xxx.xx,zk104.pulsar.xxx.xx.
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  o.a.p.z.ZooKeeperSessionWatcher      - Received zookeeper notification, eventType=None, eventState=Expired
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] ERROR o.a.p.z.ZooKeeperSessionWatcher      - ZooKeeper session already expired, invoking shutdown
01:47:09.963 [pulsar-zk-session-watcher-5-1] INFO  o.a.p.z.ZooKeeperSessionWatcher      - ZooKeeperSessionWatcher interrupted
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  o.a.p.b.MessagingServiceShutdownHook - Invoking Runtime.halt(-1)
01:47:09.964 [ZKC-connect-executor-0] INFO  o.a.b.zookeeper.ZooKeeperClient      - Reconnecting zookeeper zk100.pulsar.xxx.xx,zk101.pulsar.xxx.xx,zk102.pulsar.xxx.xx,zk103.pulsar.xxx.xx,zk104.pulsar.xxx.xx.
01:47:09.966 [ZKC-connect-executor-0] INFO  org.apache.zookeeper.ZooKeeper       - Initiating client connection, connectString=zk100.pulsar.xxx.xx,zk101.pulsar.xxx.xx,zk102.pulsar.xxx.xx,zk103.pulsar.xxx.xx,zk104.pulsar.xxx.xx sessionTimeout=30000 watcher=org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase@1c7f3bee

(Broker became down and not self-recovered)
```

**Comment by sijie** [comment] 2019-02-07 04:44
@nkurihar : 

> After ZK session expired, Broker become down.

this is current behavior. broker shutdown itself when the zookeeper session is expired. my question was "does the broker became down affect the clients?".

there is a plan on improve the logic on handling zookeeper session expires. /cc @merlimat @ivankelly

**Comment by nkurihar** [comment] 2019-02-07 05:16
@sijie 
> "does the broker became down affect the clients?".

No.
Clients successfully reconnected to another Brokers.

We are now investigating ZK logs and found a lot of ZK session expiration.
(if we find more details, we will add)

> there is a plan on improve the logic on handling zookeeper session expires.

Sounds great!

**Comment by nkurihar** [comment] 2019-02-08 02:16
We found that producing from a particular topic causes Broker's frequent GCs, and finally ZK session will be disconnected.

Configuration of the problematic namespace:
```
$ pulsar-admin namespaces policies tenant/global/ns
{
  "auth_policies" : {
    "namespace_auth" : {
      “role1" : [ "consume", "produce" ],
      “role2" : [ "produce" ]
    },
    "destination_auth" : { }
  },
  "replication_clusters" : [ “cluster1" ],
  "bundles" : {
    "boundaries" : [ "0x00000000", "0x08000000", "0x0c000000", "0x10000000", "0x20000000", "0x40000000", "0x60000000", "0x70000000", "0x78000000", "0x7c000000", "0x80000000", "0x90000000", "0x94000000", "0x98000000", "0xa0000000", "0xc0000000", "0xdfffffff", "0xe3ffffff", "0xe7ffffff", "0xefffffff", "0xffffffff" ],
    "numBundles" : 20
  },
  "backlog_quota_map" : {
    "destination_storage" : {
      "limit" : 2147483648,
      "policy" : "consumer_backlog_eviction"
    }
  },
  "clusterDispatchRate" : { },
  "deduplicationEnabled" : true,
  "latency_stats_sample_rate" : { },
  "message_ttl_in_seconds" : 86400,
  "retention_policies" : {
    "retentionTimeInMinutes" : 0,
    "retentionSizeInMB" : 0
  },
  "deleted" : false,
  "encryption_required" : false,
  "subscription_auth_mode" : "None"
}
```

Stats of the topic:
```
$ pulsar-admin persistent partitioned-stats persistent://tenant/global/ns/topicname
{
  "msgRateIn" : 13749.405145692821,
  "msgThroughputIn" : 2624357.272642204,
  "msgRateOut" : 0.0,
  "msgThroughputOut" : 0.0,
  "averageMsgSize" : 1526.9644796817477,
  "storageSize" : 16578083978,
  "publishers" : [ {
    "msgRateIn" : 916.2981245138371,
    "msgThroughputIn" : 174944.0752240065,
    "averageMsgSize" : 1524.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 915.2981268948027,
    "msgThroughputIn" : 174631.82621486855,
    "averageMsgSize" : 1523.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 916.7314553536784,
    "msgThroughputIn" : 174855.3587149024,
    "averageMsgSize" : 1523.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 917.2147881797507,
    "msgThroughputIn" : 175129.79147638264,
    "averageMsgSize" : 1523.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 916.1981230730042,
    "msgThroughputIn" : 175036.92487912314,
    "averageMsgSize" : 1525.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 915.0814587846285,
    "msgThroughputIn" : 174646.9091628056,
    "averageMsgSize" : 1523.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 918.5981173215638,
    "msgThroughputIn" : 175195.25776490584,
    "averageMsgSize" : 1521.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 916.2481204650497,
    "msgThroughputIn" : 174752.4751328054,
    "averageMsgSize" : 1521.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 917.6814516742087,
    "msgThroughputIn" : 175117.62447102348,
    "averageMsgSize" : 1522.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 917.7647840932245,
    "msgThroughputIn" : 175091.40764492872,
    "averageMsgSize" : 1522.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 915.7481213786745,
    "msgThroughputIn" : 174828.69157140085,
    "averageMsgSize" : 1523.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 915.8814529493387,
    "msgThroughputIn" : 174970.22430954664,
    "averageMsgSize" : 1525.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 916.4647860260764,
    "msgThroughputIn" : 174818.74155270297,
    "averageMsgSize" : 1522.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 916.8647852416252,
    "msgThroughputIn" : 175094.0242297361,
    "averageMsgSize" : 1524.0,
    "producerId" : 0
  }, {
    "msgRateIn" : 917.3314497433578,
    "msgThroughputIn" : 175243.94029306492,
    "averageMsgSize" : 1524.0,
    "producerId" : 0
  } ],
  "subscriptions" : {
    “sub1" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "msgRateRedeliver" : 0.0,
      "msgBacklog" : 86915729,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "unackedMessages" : 0,
      "msgRateExpired" : 0.0,
      "consumers" : [ ]
    }
  },
  "replication" : { },
  "metadata" : {
    "partitions" : 8
  },
  "partitions" : { }
} 
```
Stats internal of an internal-topic
```
$ sudo pulsar-admin persistent stats-internal persistent://tenant/global/ns/topicname-partition-0
{
  "entriesAddedCounter" : 12087378,
  "numberOfEntries" : 11110595,
  "totalSize" : 2107489222,
  "currentLedgerEntries" : 669812,
  "currentLedgerSize" : 126853597,
  "lastLedgerCreatedTimestamp" : "2019-02-08T11:01:42.848+09:00",
  "waitingCursorsCount" : 0,
  "pendingAddEntriesCount" : 0,
  "lastConfirmedEntry" : "9287653:669811",
  "state" : "LedgerOpened",
  "ledgers" : [ {
    "ledgerId" : 9282667,
    "entries" : 935065,
    "size" : 177983818
  }, {
    "ledgerId" : 9282876,
    "entries" : 959774,
    "size" : 182570651
  }, {
    "ledgerId" : 9283069,
    "entries" : 980610,
    "size" : 186309626
  }, {
    "ledgerId" : 9283292,
    "entries" : 996760,
    "size" : 189755206
  }, {
    "ledgerId" : 9283585,
    "entries" : 1122265,
    "size" : 212600168
  }, {
    "ledgerId" : 9283938,
    "entries" : 1142511,
    "size" : 216121699
  }, {
    "ledgerId" : 9284223,
    "entries" : 1130209,
    "size" : 213851655
  }, {
    "ledgerId" : 9286911,
    "entries" : 1074060,
    "size" : 203609877
  }, {
    "ledgerId" : 9287187,
    "entries" : 1054774,
    "size" : 199907614
  }, {
    "ledgerId" : 9287401,
    "entries" : 1044755,
    "size" : 197925311
  }, {
    "ledgerId" : 9287653,
    "entries" : 0,
    "size" : 0
  } ],
  "cursors" : {
    "sub1" : {
      "markDeletePosition" : "9282667:265388",
      "readPosition" : "9282667:265389",
      "waitingReadOp" : false,
      "pendingReadOps" : 0,
      "messagesConsumedCounter" : 1242172,
      "cursorLedger" : 9282647,
      "cursorLedgerLastEntry" : 10,
      "individuallyDeletedMessages" : "[]",
      "lastLedgerSwitchTimestamp" : "2019-02-08T09:11:42.684+09:00",
      "state" : "Open",
      "numberOfEntriesSinceFirstNotAckedMessage" : 1,
      "totalNonContiguousDeletedMessagesRange" : 0,
      "properties" : { }
    },
    "pulsar.dedup" : {
      "markDeletePosition" : "9287653:669433",
      "readPosition" : "9287653:669434",
      "waitingReadOp" : false,
      "pendingReadOps" : 0,
      "messagesConsumedCounter" : 12087000,
      "cursorLedger" : 9282463,
      "cursorLedgerLastEntry" : 699,
      "individuallyDeletedMessages" : "[]",
      "lastLedgerSwitchTimestamp" : "2019-02-08T09:11:42.683+09:00",
      "state" : "Open",
      "numberOfEntriesSinceFirstNotAckedMessage" : 1,
      "totalNonContiguousDeletedMessagesRange" : 0,
      "properties" : {
        "cluster1-449-127492" : 60260034,
        "cluster1-449-127493" : 60262711,
        "cluster1-449-127495" : 60264335,
        "cluster1-449-127497" : 60261591,
        "cluster1-449-127499" : 60263472,
        "cluster1-449-127501" : 60262324,
        "cluster1-449-127503" : 60259581,
        "cluster1-449-127505" : 60265239,
        "cluster1-449-127507" : 60263064,
        "cluster1-449-127509" : 60263894,
        "cluster1-449-127511" : 60264359,
        "cluster1-449-127513" : 60263808,
        "cluster1-449-127515" : 60259626,
        "cluster1-449-127517" : 60263209,
        "cluster1-449-127519" : 60260679
      }
    }
  }
}
```
* the number of partition: 8
*  deduplicationEnabled : true
* message_ttl_in_seconds : 86400
* There is no consumer. Thus the backlog is always full and messages are discarded 
 every time by the policy: "consumer_backlog_eviction"

**Comment by nkurihar** [comment] 2019-02-09 11:05
Disabling deduplication seems to suppress GCs.
We will investigate more detail.

**Comment by hrsakai** [comment] 2019-02-14 04:05
We kept producing messages for 4 hours and memory usage of broker became as follow:
 ```
Deduplication disabled : 50G
Deduplication enabled: 99G(Reached 99G and full GC occured)
 ```

If deduplication is disabled, memory usage remained at 50G all the time. On the other hand, if deduplication is enabled, memory usage gradually increased from 50G to 99G.
 
■memory settings
-Xms96g -Xmx96g -XX:MaxDirectMemorySize=96g

■deduplication settings
brokerDeduplicationMaxNumberOfProducers=10000
brokerDeduplicationEntriesInterval=1000
brokerDeduplicationProducerInactivityTimeoutMinutes=360
 
■the number of partition
8
(We used a partitioned topic for test)
  
■Rate
20,000msg/s(2,500msg/s per internal topic)
 
■Message size
200byte
 
■Execution time
4hours

**Comment by merlimat** [comment] 2019-02-14 04:11
@hrsakai can you share a `jmap histo:live` of the process with dedup turned on?

**Comment by hrsakai** [comment] 2019-02-14 12:21
@merlimat 
Here are outouts of `jmap -histo`.
[jmap-histo.txt](https://github.com/apache/pulsar/files/2864880/jmap-histo.txt)
[jmap-histo-live.txt](https://github.com/apache/pulsar/files/2864881/jmap-histo-live.txt)

Specs of this broker is different from those of a broker in the above test.
So, memory settings of this broker is different:
```
-Xms3g -Xmx3g
```

Full GC log (caused by `jmap histo:live`)
```
2019-02-14T21:02:53.684+0900: 38477.063: [Full GC (Heap Inspection Initiated GC)  1222M->125M(3072M), 2.4529610 secs]
   [Eden: 61.0M(1416.0M)->0.0B(1536.0M) Survivors: 120.0M->0.0B Heap: 1222.8M(3072.0M)->125.7M(3072.0M)], [Metaspace: 74890K->74877K(1118208K)]
 [Times: user=1.41 sys=0.00, real=2.45 secs]
```

**Comment by ivankelly** [comment] 2019-02-14 12:35
@hrsakai is this on a single topic? The histogram points to there being a lot of entries in the ManagedCursorContainer. There should only be one managed cursor for deduplication for each topic. So either something is triggering the creation and destruction of the dedupe cursors in a loop, or something about having any dedupe cursor at all is causing bad behaviour from the other cursors.

Can you try enabling debug logging for org.apache.pulsar.broker.service.persistent.MessageDeduplication?

If that doesn't yield info, then we'll have to do a heap dump.

**Comment by hrsakai** [comment] 2019-02-15 00:42
@ivankelly 
At this time, I produced messages to a partitioned topic (16 partitions).
And There are 4 producers, 0 consumer and 1 subscription.

> Can you try enabling debug logging for org.apache.pulsar.broker.service.persistent.MessageDeduplication? 

The broker outputed a lot of logs as follow:
```
08:33:16.719 [bookkeeper-ml-workers-OrderedExecutor-3-0] DEBUG o.a.p.b.s.p.MessageDeduplication     - [persistent://XXXXX/global/deduplication/p-topic2-partition-3] Taking snapshot of sequence ids map
08:33:16.719 [bookkeeper-ml-workers-OrderedExecutor-3-0] DEBUG o.a.p.b.s.p.MessageDeduplication     - [persistent://XXXXX/global/deduplication/p-topic2-partition-3] Stored new deduplication snapshot at 790835:45361
08:33:16.719 [bookkeeper-ml-workers-OrderedExecutor-3-0] DEBUG o.a.p.b.s.p.MessageDeduplication     - [persistent://XXXXX/global/deduplication/p-topic2-partition-3] Taking snapshot of sequence ids map
08:33:16.719 [bookkeeper-ml-workers-OrderedExecutor-3-0] DEBUG o.a.p.b.s.p.MessageDeduplication     - [persistent://XXXXX/global/deduplication/p-topic2-partition-3] Stored new deduplication snapshot at 790835:45362
08:33:16.719 [bookkeeper-ml-workers-OrderedExecutor-3-0] DEBUG o.a.p.b.s.p.MessageDeduplication     - [persistent://XXXXX/global/deduplication/p-topic2-partition-3] Taking snapshot of sequence ids map
08:33:16.719 [bookkeeper-ml-workers-OrderedExecutor-3-0] DEBUG o.a.p.b.s.p.MessageDeduplication     - [persistent://XXXXX/global/deduplication/p-topic2-partition-3] Stored new deduplication snapshot at 790835:45363
08:33:16.719 [bookkeeper-ml-workers-OrderedExecutor-1-0] DEBUG o.a.p.b.s.p.MessageDeduplication     - [persistent://XXXXX/global/deduplication/p-topic2-partition-5] Taking snapshot of sequence ids map
08:33:16.719 [bookkeeper-ml-workers-OrderedExecutor-1-0] DEBUG o.a.p.b.s.p.MessageDeduplication     - [persistent://XXXXX/global/deduplication/p-topic2-partition-5] Stored new deduplication snapshot at 790833:57439
08:33:16.719 [bookkeeper-ml-workers-OrderedExecutor-1-0] DEBUG o.a.p.b.s.p.MessageDeduplication     - [persistent://XXXXX/global/deduplication/p-topic2-partition-9] Taking snapshot of sequence ids map
08:33:16.719 [bookkeeper-ml-workers-OrderedExecutor-1-0] DEBUG o.a.p.b.s.p.MessageDeduplication     - [persistent://XXXXX/global/deduplication/p-topic2-partition-9] Stored new deduplication snapshot at 790831:57486
.
.
```

`brokerDeduplicationEntriesInterval` is 1 on this broker. This may be affecting.
However,  this issue occurs even if `brokerDeduplicationEntriesInterval` is default value(1000).

**Comment by ivankelly** [comment] 2019-02-15 11:22
what is the publication rate to this topic?

**Comment by hrsakai** [comment] 2019-02-15 13:30
@ivankelly
It is about 20000〜40000msg/s.
(5000〜10000msg/producer)

**Comment by ivankelly** [comment] 2019-02-15 14:00
The histograms you sent only show 2.4GB and 131MB of objects respectively. Did you take them when the bad behaviour was happening?

How long does it take to grow from 50G to 99G.

**Comment by hrsakai** [comment] 2019-02-15 23:26
@ivankelly

The broker I took histograms is different from the broker grow from 50G to 99G.
heap size of the broker I took histograms is only 3G.
But, it seems that same problem is happening.

> How long does it take to grow from 50G to 99G.

it take about 4hours.

**Comment by merlimat** [comment] 2019-02-16 00:38
@hrsakai I think #3612 should be fixing this. I was able to reproduce the behavior locally (with a smaller heap).

**Comment by hrsakai** [comment] 2019-02-16 13:26
@merlimat 
Thanks for fix. I will try to test again with that code.

**Comment by merlimat** [comment] 2019-03-06 23:57
As @hrsakai pointed out, the fix was ineffective because applied on a code path that's not being used. 

The problem is that that while the cursor is set as "inactive" in the beginning, a periodic check is flipping back the state to "active": 

https://github.com/apache/pulsar/blob/43380523c5269c152f61b2aa8f7b70281c770d1d/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L878-L885

Working on a fix.

**Comment by merlimat** [comment] 2019-03-07 02:36
Updated #3612 with correct fix

**Closed** 2019-03-08 11:05 UTC
Labels: component/broker, triage/week-6, type/bug
