### ISSUE TITLE
[Broker] handleSubscribe read_compacted not exists

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar#9210] opened 2021-01-14 15:48 UTC
**Describe the bug**
Running master, without old proxies/clients there are issues on subscription `read_compacted` does not exist.

There is breaking changes?

**Comment by codelipenghui** [comment] 2021-01-19 03:46
@KannarFr with old proxy/client or without old proxy/client?

**Comment by KannarFr** [comment] 2021-01-19 12:41
@codelipenghui with old, I guessed it was breaking changes, but can't find issue/mention about it, can you link me or explain?

**Comment by codelipenghui** [comment] 2021-01-24 01:55
@KannarFr Could you please provide the steps of reproducing this issue? I don’t remember compaction related changes are introduced currently.

**Comment by codelipenghui** [comment] 2021-03-02 04:07
Close this one first since no update.

**Closed by codelipenghui** 2021-03-02 04:07 UTC
Labels: type/bug
