### ISSUE TITLE
running in docker throws exception

### ISSUE THREAD

**Issue by epitka** [apache/pulsar#15746] opened 2022-05-24 08:15 UTC
**Describe the bug**
Following steps on how to run docker for local as described here https://pulsar.apache.org/docs/getting-started-docker

Getting following exception
```
WARNING: An illegal reflective access operation has occurred                                                                                                                             
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/pulsar/lib/io.netty-netty-common-4.1.74.Final.jar) to constructor java.nio.DirectByteBuffer(long,int) 
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil                                                                                      
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations                                                                                    
WARNING: All illegal access operations will be denied in a future release                                                                                                                
2022-05-24T07:43:39,292+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Running 1 bookie(s) and advertised them at 127.0.0.1.                                    
2022-05-24T07:43:39,295+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Starting ZK server                                                                       
2022-05-24T07:43:39,296+0000 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.                                                                    
java.nio.file.AccessDeniedException: /pulsar/data/standalone                                                                                                                             
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]                                                                                                 
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]                                                                                                  
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]                                                                                                  
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]                                                                                     
        at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]                                                                                                                    
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]                                                                                                          
        at java.nio.file.Files.createDirectories(Files.java:783) ~[?:?]                                                                                                                  
        at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runZookeeper(LocalBookkeeperEnsemble.java:190) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]              
        at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:443) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]           
        at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:269) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]                                                      
        at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:139) [org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]                                          
```
                                                                                                                                                                                         

**To Reproduce**
 docker run -it -p 6650:6650  -p 8080:8080 --name pulsar_standalone --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:2.10.0 bin/pulsar standalone

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

Same issue is with latest image of docker

Also, starting container from the docker desktop yields "Access Denied Exception" as shown below

```
WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/pulsar/lib/io.netty-netty-common-4.1.74.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)

WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

2022-05-24T07:43:39,292+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Running 1 bookie(s) and advertised them at 127.0.0.1.

2022-05-24T07:43:39,295+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Starting ZK server

2022-05-24T07:43:39,296+0000 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.

java.nio.file.AccessDeniedException: /pulsar/data/standalone

at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]

at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]

at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]

at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]

at java.nio.file.Files.createDirectories(Files.java:783) ~[?:?]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runZookeeper(LocalBookkeeperEnsemble.java:190) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:443) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:269) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:139) [org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/pulsar/lib/io.netty-netty-common-4.1.74.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)

WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

2022-05-24T07:50:04,922+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Running 1 bookie(s) and advertised them at 127.0.0.1.

2022-05-24T07:50:04,926+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Starting ZK server

2022-05-24T07:50:04,927+0000 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.

java.nio.file.AccessDeniedException: /pulsar/data/standalone

at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]

at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]

at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]

at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]

at java.nio.file.Files.createDirectories(Files.java:783) ~[?:?]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runZookeeper(LocalBookkeeperEnsemble.java:190) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:443) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:269) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:139) [org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/pulsar/lib/io.netty-netty-common-4.1.74.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)

WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

2022-05-24T07:50:51,476+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Running 1 bookie(s) and advertised them at 127.0.0.1.

2022-05-24T07:50:51,480+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Starting ZK server

2022-05-24T07:50:51,481+0000 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.

java.nio.file.AccessDeniedException: /pulsar/data/standalone

at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]

at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]

at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]

at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]

at java.nio.file.Files.createDirectories(Files.java:783) ~[?:?]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runZookeeper(LocalBookkeeperEnsemble.java:190) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:443) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:269) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:139) [org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/pulsar/lib/io.netty-netty-common-4.1.74.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)

WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

2022-05-24T07:51:03,960+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Running 1 bookie(s) and advertised them at 127.0.0.1.

2022-05-24T07:51:03,963+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Starting ZK server

2022-05-24T07:51:03,964+0000 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.

java.nio.file.AccessDeniedException: /pulsar/data/standalone

at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]

at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]

at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]

at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]

at java.nio.file.Files.createDirectories(Files.java:783) ~[?:?]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runZookeeper(LocalBookkeeperEnsemble.java:190) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:443) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:269) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:139) [org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/pulsar/lib/io.netty-netty-common-4.1.74.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)

WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

2022-05-24T07:58:19,534+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Running 1 bookie(s) and advertised them at 127.0.0.1.

2022-05-24T07:58:19,537+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Starting ZK server

2022-05-24T07:58:19,540+0000 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.

java.nio.file.AccessDeniedException: /pulsar/data/standalone

at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]

at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]

at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]

at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]

at java.nio.file.Files.createDirectories(Files.java:783) ~[?:?]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runZookeeper(LocalBookkeeperEnsemble.java:190) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:443) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:269) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:139) [org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/pulsar/lib/io.netty-netty-common-4.1.74.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)

WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

2022-05-24T07:59:06,817+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Running 1 bookie(s) and advertised them at 127.0.0.1.

2022-05-24T07:59:06,820+0000 [main] INFO  org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble - Starting ZK server

2022-05-24T07:59:06,821+0000 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.

java.nio.file.AccessDeniedException: /pulsar/data/standalone

at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]

at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]

at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]

at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]

at java.nio.file.Files.createDirectories(Files.java:783) ~[?:?]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.runZookeeper(LocalBookkeeperEnsemble.java:190) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.startStandalone(LocalBookkeeperEnsemble.java:443) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:269) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:139) [org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]

​

```

**Comment by shibd** [comment] 2022-05-24 16:22
I reproduce this on MAC OS, i will try to fix it.

**Comment by michaeljmarshall** [comment] 2022-05-25 05:52
@shibd - just so you know, it looks like #15769 is a proposed solution.

**Comment by drianpauL** [comment] 2022-05-26 01:23
Yes, this issue is a duplicate of issue #15230

**Closed** 2022-05-26 04:23 UTC
Labels: type/bug
