### ISSUE TITLE
Improve the internal Jersey Client to use a Connection Pool

### ISSUE THREAD

**Issue by poorbarcode** [apache/pulsar#22003] opened 2024-01-31 03:13 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

As many connections as there are requests are used by the internal Jersey Client.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by lhotari** [comment] 2024-02-09 16:44
pulsar-client-admin uses AsyncHttpClient , I created #22041 for addressing that.

Jetty client is used in the Pulsar Proxy [for proxying /admin endpoint](https://github.com/apache/pulsar/blob/master/pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/AdminProxyHandler.java).

Where do we have a Jersey client?

**Comment by lhotari** [comment] 2024-02-09 16:50
This issue seems to be a duplicate of #22041. The AsyncHttpClient is used as a Jersey client connector in pulsar-client-admin. I'll close this ticket since #22041 contains a better issue description.

**Closed by lhotari** 2024-02-09 16:50 UTC
