### ISSUE TITLE
When ttlDurationDefaultInSeconds is set the messages are expired one by one every 5 minutes even before ttlDurationDefaultInSeconds is reached

### ISSUE THREAD

**Issue by AmitANetskope** [apache/pulsar#6617] opened 2020-03-26 10:30 UTC
Messages are being expired even before ttlDurationDefaultInSeconds is reached when ttlDurationDefaultInSeconds is set.

**To Reproduce**
1. in broker conf auto topic creation is enabled
2. in broker set ttlDurationDefaultInSeconds to 604800 (in all brokers and restart them)
3. now create subscription to topic - persistent/public/default/amit_test
4. close the subscription
5. create producer to above topic - providing a name and setting timeout to 0 (also dedup has been enabled in broker conf)
6. Now send 2 messages to the topic using the producer one after another
7. Now close the producer and client
8. Now using admin stats monitor the topic - pulsar-broker:8080/admin/v2/persistent/public/default/amit_test/stats
9. under the subscription can see that 2 messages are present in msgBacklog and lastExpireTimestamp is 0 (and no active producers or consumers)
10. After couple of minutes can observe msgBacklog reduced to 1 and lastExpireTimestamp is set to recent timestamp
11. After 5 more min can observe msgBacklog reduced to 0 and lastExpireTimestamp is updated to recent timestamp

**Expected behavior**
Messages should not be expired until ttl is reached.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Pulsar version - 2.5.0

**Comment by codelipenghui** [comment] 2020-03-30 14:41
@AmitANetskope The `lastExpireTimestamp` updates when the task of message expiration triggers, so the recent timestamp is an expected value. I have tried on my laptop and I add a test #6638 to ensure messages do not expire early, but can't reproduce your problem. Is the problem appears frequently or not?  And if you can reproduce it, could you please add your server log here? This will help find the problem.

**Comment by AmitANetskope** [comment] 2020-03-30 15:44
Broker log file - 
[pulsar-broker-pulsar-broker-1.log](https://github.com/apache/pulsar/files/4403853/pulsar-broker-pulsar-broker-1.log)

{noformat}
15:23:41.554 [pulsar-web-30-3] INFO  org.eclipse.jetty.server.RequestLog - 182.75.130.70 - - [30/Mar/2020:15:23:41 +0000] "GET /admin/v2/persistent/public/amit_test/amit_test/stats?authoritative=true HTTP/1.1" 200 522 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0" 7
15:24:11.396 [pulsar-msg-expiry-monitor-25-1] INFO  org.apache.pulsar.broker.service.persistent.PersistentMessageExpiryMonitor - [persistent://public/amit_test/amit_test][amit_test] Starting message expiry check, ttl= 604800 seconds
15:24:11.453 [bookkeeper-ml-workers-OrderedExecutor-5-0] INFO  org.apache.pulsar.broker.service.persistent.PersistentMessageExpiryMonitor - [persistent://public/amit_test/amit_test][amit_test] Expiring all messages until position 406:0
15:24:36.719 [pulsar-web-30-7] INFO  org.eclipse.jetty.server.RequestLog - 182.75.130.70 - - [30/Mar/2020:15:24:36 +0000] "GET /admin/v2/persistent/public/amit_test/amit_test/stats?authoritative=true HTTP/1.1" 200 551 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0" 5
15:27:57.092 [pulsar-web-30-7] INFO  org.eclipse.jetty.server.RequestLog - 182.75.130.70 - - [30/Mar/2020:15:27:57 +0000] "GET /admin/v2/persistent/public/amit_test/amit_test/stats?authoritative=true HTTP/1.1" 200 551 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0" 8
15:28:49.569 [pulsar-web-30-8] INFO  org.eclipse.jetty.server.RequestLog - 182.75.130.70 - - [30/Mar/2020:15:28:49 +0000] "GET /admin/v2/persistent/public/amit_test/amit_test/stats?authoritative=true HTTP/1.1" 200 551 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0" 5
15:28:55.099 [pulsar-web-30-4] INFO  org.eclipse.jetty.server.RequestLog - 182.75.130.70 - - [30/Mar/2020:15:28:55 +0000] "GET /admin/v2/persistent/public/amit_test/amit_test/stats?authoritative=true HTTP/1.1" 200 551 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0" 6
15:29:11.394 [pulsar-msg-expiry-monitor-25-1] INFO  org.apache.pulsar.broker.service.persistent.PersistentMessageExpiryMonitor - [persistent://public/amit_test/amit_test][amit_test] Starting message expiry check, ttl= 604800 seconds
15:29:11.412 [bookkeeper-ml-workers-OrderedExecutor-5-0] INFO  org.apache.pulsar.broker.service.persistent.PersistentMessageExpiryMonitor - [persistent://public/amit_test/amit_test][amit_test] Expiring all messages until position 406:1
{noformat}

**Comment by sijie** [comment] 2020-03-31 22:06
@AmitANetskope I think the issue has been fixed by #6211. I also verified it. It will be included in the upcoming 2.5.1 release. 

For testing purpose, you can try out our weekly build: https://github.com/streamnative/pulsar/releases/tag/v2.6.0-347d3851b

It includes that fix.

**Comment by sijie** [comment] 2020-04-08 02:19
Closed the issue since it is already fixed by #6211

**Closed by sijie** 2020-04-08 02:19 UTC
Labels: triage/week-14, type/bug
