### ISSUE TITLE
Behavior of redelivery and ackTimeout in Java client

### ISSUE THREAD

**Issue by cbornet** [apache/pulsar#3059] opened 2018-11-26 17:07 UTC
#### Expected behavior

With the Java client, when `ackTimeout` is specified for a consumer, unacked individual messages should be resent only after `ackTimeout` has expired.

#### Actual behavior

Unacked messages are all resent at once every `ackTimeout` period.

#### Steps to reproduce

Run this program
```java
public class UnackedTrackerIssue {
    private static ExecutorService executor = Executors.newFixedThreadPool(10);

    public static void main(String[] args) throws PulsarClientException, InterruptedException {

        final String topic = "my-topic";

        PulsarClient client = PulsarClient.builder()
                .serviceUrl("pulsar://localhost:6650")
                .build();

        Consumer<byte[]> consumer = client.newConsumer()
                .topic(topic)
                .subscriptionName(UUID.randomUUID().toString())
                .ackTimeout(5, TimeUnit.SECONDS)
                .subscribe();

        receive(consumer);

        Producer<byte[]> producer = client.newProducer()
                .topic(topic)
                .create();

        for(int i=0;i<5; i++) {
            Thread.sleep(1000);
            producer.send(("" + i).getBytes());
        }

    }

    private static void receive(Consumer<byte[]> consumer) {
        consumer.receiveAsync()
                .thenAccept(msg -> {
                    System.out.println("" + Instant.now() + " consume " + new String(msg.getData()));
                    executor.execute(() -> receive(consumer));
                });
    }
}
```
Output is something like:

2018-11-26T16:51:04.555Z consume 0
2018-11-26T16:51:05.552Z consume 1
2018-11-26T16:51:06.558Z consume 2
**2018-11-26T16:51:07.565Z consume 3**
2018-11-26T16:51:08.323Z consume 0
2018-11-26T16:51:08.324Z consume 1
2018-11-26T16:51:08.325Z consume 2
**2018-11-26T16:51:08.329Z consume 3**
2018-11-26T16:51:08.574Z consume 4
2018-11-26T16:51:13.327Z consume 0
2018-11-26T16:51:13.329Z consume 1
2018-11-26T16:51:13.330Z consume 2
**2018-11-26T16:51:13.330Z consume 3**
2018-11-26T16:51:13.331Z consume 4

The delay of redelivery between the message "3" occurences should be about 5 seconds but the first time there's only 1s.

Code that results in this behavior : https://github.com/apache/pulsar/blob/0ab2325fa33231f1c69782e081483012467dfcab/pulsar-client/src/main/java/org/apache/pulsar/client/impl/UnAckedMessageTracker.java#L87

#### System configuration
**Pulsar version**: master https://github.com/apache/pulsar/commit/fe2c8ee4d37e2a45dfb528592915746827416e18

**Comment by codelipenghui** [comment] 2018-11-28 01:45
I tried the program in java client version 2.1.0-incubating
```
2018-11-28T01:34:26.493Z consume 0
2018-11-28T01:34:27.498Z consume 1
2018-11-28T01:34:28.515Z consume 2
2018-11-28T01:34:29.553Z consume 3
2018-11-28T01:34:30.571Z consume 4
2018-11-28T01:34:35.178Z consume 0
2018-11-28T01:34:35.179Z consume 1
2018-11-28T01:34:35.179Z consume 2
2018-11-28T01:34:35.180Z consume 3
2018-11-28T01:34:35.180Z consume 4
2018-11-28T01:34:45.184Z consume 0
2018-11-28T01:34:45.184Z consume 1
2018-11-28T01:34:45.185Z consume 2
2018-11-28T01:34:45.185Z consume 3
2018-11-28T01:34:45.186Z consume 4
```
@jiazhai 
looks like caused by the PR #2590

**Comment by sijie** [comment] 2018-11-28 21:40
@jiazhai can you take a look at this? as @codelipenghui pointed out, it seems to be a regression from #2590

**Comment by cbornet** [comment] 2018-11-28 22:37
Was it really better before ? The message "0" is sent the first time at 34:26 and the second time at 34:35 where one would have expected to get it at 34:31. And the period of redelivery afterwards is 10s instead of 5s.
I think the problem comes that redelivery is done in batch, not taking into account the actual arrival time of the message. Now I understand that asking redelivery individually may impact the perf...

**Comment by jiazhai** [comment] 2018-11-30 01:30
will look into it

**Comment by jiazhai** [comment] 2018-12-03 03:04
Seems indeed as @cbornet mentioned, changes in PR #2590 make it worse. I would like to use this issue to revert changes in #2590. 

But as @codelipenghui requirement, we should make a more accurate redeliver. 
A way todo this is that: 
split acktimeout into several time-slots, and introduce a timewheel to do the redeliver for each time-slots, the more time-slots user set, the more accurate it will be.

**Comment by jiazhai** [comment] 2019-01-23 02:13
close this issue since penghui's prs merged.

**Closed by jiazhai** 2019-01-23 02:13 UTC
Labels: component/client, triage/week-48, type/bug
