### ISSUE TITLE
[Doc] Documentation site search navigates to the end of the page

### ISSUE THREAD

**Issue by sara-hannigan** [apache/pulsar#18960] opened 2022-12-16 22:30 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### What issue do you find in Pulsar docs?

Documentation site search navigates to the end of the page

I've attached an example, and this happens intermittently (up to 50% of the time)

#### Steps to reproduce

1. Type search term into search bar
2. Click on the search
3. See it go to the bottom of the page

This appears to mostly happen during the first search or in-text search

### What is your suggestion?

Have the search take to the relevant piece of the page or the top of the page.

### Any reference?

https://drive.google.com/file/d/1s9xuYEUcJ9-BLFt2Mc2IiwWCfh-pi-Ke/view?usp=sharing - video

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment] 2022-12-17 06:50
Hi @sara-hannigan may you attach a screen recording or reproduce steps? It's quite vague from such descriptions.

**Comment by urfreespace** [comment] 2023-01-12 06:03
> OK. I get the point now. I have met this issue ever that the anchor doesn't work as expected. It may not be caused by the search mechanism but by anchor resolution.
> 
> cc @urfreespace do you have some insight here? I'm not quite familiar with this part.

It looks like the URLs from searching crawler responses have an anchor attached to them so the page will auto-scroll to the anchor position, the URLs were history records but the page content maybe had a new update that some old anchor is removed so the anchor jump will not correctly, however after a new crawler indexing is done some search result will become correct but they're not guaranteed to be all correct, I think anchor jump is not guaranteed, and this has something to do with page rendering time, however no more idea about this issue on my side. /cc @sara-hannigan

**Comment by tisonkun** [comment] 2023-02-01 16:55
Thanks for your explanation @urfreespace!

Closed as expected or at least won't fix by now.

**Closed by tisonkun** 2023-02-01 16:55 UTC
Labels: doc-required
