### ISSUE TITLE
Flaky-test: PulsarOffsetBackingStoreTest.testGetSet

### ISSUE THREAD

**Issue by codelipenghui** [apache/pulsar#16990] opened 2022-08-08 09:43 UTC
[example failure](https://github.com/apache/pulsar/runs/7714287203?check_suite_focus=true)

```
  Error:  Tests run: 17, Failures: 1, Errors: 0, Skipped: 15, Time elapsed: 58.95 s <<< FAILURE! - in org.apache.pulsar.io.kafka.connect.PulsarOffsetBackingStoreTest
  Error:  testGetSet(org.apache.pulsar.io.kafka.connect.PulsarOffsetBackingStoreTest)  Time elapsed: 0.236 s  <<< FAILURE!
  java.lang.AssertionError: expected [9] but found [10]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:907)
  	at org.testng.Assert.assertEquals(Assert.java:917)
  	at org.apache.pulsar.io.kafka.connect.PulsarOffsetBackingStoreTest.testGetSet(PulsarOffsetBackingStoreTest.java:163)
  	at org.apache.pulsar.io.kafka.connect.PulsarOffsetBackingStoreTest.testGetSet(PulsarOffsetBackingStoreTest.java:126)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

**Comment by mattisonchao** [comment] 2022-08-10 11:31
I think this problem may caused by #16968 and fixed by #17018.
Currently, the fix PR already merged, maybe we can close this issue until we got it again.

**Closed by mattisonchao** 2022-08-10 11:31 UTC
Labels: component/test, flaky-tests

**Comment by lhotari** [comment] 2023-10-30 06:26
Recent failure: https://github.com/apache/pulsar/actions/runs/6688692333/job/18171380708?pr=21460#step:10:679
```
  Error:  Tests run: 21, Failures: 1, Errors: 0, Skipped: 19, Time elapsed: 71.801 s <<< FAILURE! - in org.apache.pulsar.io.kafka.connect.PulsarOffsetBackingStoreTest
  Error:  org.apache.pulsar.io.kafka.connect.PulsarOffsetBackingStoreTest.testGetSet  Time elapsed: 0.417 s  <<< FAILURE!
  java.lang.AssertionError: expected [8] but found [10]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1418)
  	at org.testng.Assert.assertEquals(Assert.java:1382)
  	at org.testng.Assert.assertEquals(Assert.java:1428)
  	at org.apache.pulsar.io.kafka.connect.PulsarOffsetBackingStoreTest.testGetSet(PulsarOffsetBackingStoreTest.java:157)
  	at org.apache.pulsar.io.kafka.connect.PulsarOffsetBackingStoreTest.testGetSet(PulsarOffsetBackingStoreTest.java:120)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  ```

**Comment by lhotari** [comment] 2023-10-30 07:51
Logs for the most recent failure: https://gist.github.com/lhotari/456f811efa0f45e5170eca2e50b5c69c
