### ISSUE TITLE
Metadata Deserialization failed

### ISSUE THREAD

**Issue by 315157973** [apache/pulsar#12909] opened 2021-11-22 03:52 UTC
**Describe the bug**
When we run the unit test of the Master branch locally, the following exception occurs.

![image](https://user-images.githubusercontent.com/9758905/142798221-840b667d-6554-471d-a9f9-cdc6a2e9717d.png)

![image](https://user-images.githubusercontent.com/9758905/142798344-3b8377d4-8a9b-4a6d-a4e6-4ec5404272ef.png)

**To Reproduce**
1. checkout to master branch
2. Run some unit test in IDEA, such as `ReplicatorTest`

**Expected behavior**
No exception should occurs

**Comment by Jason918** [comment] 2021-11-23 07:09
Duplicate of #12894

**Comment by Technoboy-** [comment] 2021-12-01 08:51
This issue is fix by [apache/pulsar#12896](https://github.com/apache/pulsar/pull/12896)

**Closed by Technoboy-** 2021-12-01 08:51 UTC
Labels: type/bug
